### ISSUE TITLE
Relating to new blocks being credited in wallet but not CoiniumServ - LiteCoinPlus

### ISSUE THREAD

**Issue by arebias** [bonesoul/CoiniumServ#1020]
Found Block > Wallet Credited > Miner Not Paid > Miner Showing Block Found

debug.log Info: 

04/26/2018 05:00:54 -04:00 [Debug] [ShareManager] [LiteCoinPlus] We thought a block was found but it was rejected by the coin daemon; [991783c3a69ec3957995205089d3fe7c1fa91a48d98b05933e9169af5c3287dd] - reason; Block not found

litecoinplus.json

{
    "name": "LiteCoinPlus",
    "symbol": "LCP",
    "algorithm": "scrypt",
    "site": "http://litecoinplus.co/",
    "blockExplorer": {
        "block": "http://lcp.altcoinwarz.com:3004/block/block.dws?",
        "tx": "http://lcp.altcoinwarz.com:3004/tx/tx.dws?",
        "address": "http://lcp.altcoinwarz.com:3004/address/address.dws?"
    }
}

Any suggestions on changes that should be made to litecoinplus.json or anywhere else?

Also, API Pool Stats reports the following:

"config": {
    "coin": {
      **"rpcupdate": false,**        _<<<--------  Question Is Why Does This Say False -------- ????
      "name": "LiteCoinPlus",
      "symbol": "LCP",
      "algorithm": "scrypt",
      "site": "http://litecoinplus.co/"
    },

**Comment by flyx2888** [comment]
@arebias 

What is the payments minimum set to? Miner's will not be paid until the payments minimum threshold is met.

"rpcupdate": false <- This will always be false unless set to true in the coin conf. It is a specific fix to validate wallet addresses when you receive this error: "Halted as daemon we are connected to does not own the pool address". More info regarding this fix can be seen here:

https://github.com/bonesoul/CoiniumServ/issues/975

**Comment by arebias** [comment]
@flyx2888 

Coin Threshold:

"payments": {
		"enabled": true,
        "interval": 60,
		"minimum": 0.01
	},

I should have added in the above sequence the last one added below. 

Found Block > Wallet Credited > Miner Not Paid > Miner Showing Block Found > _CoiniumServ Not Showing Block Found_

I know that is an issue that was mentioned in another post but the other person had not added their coin.json so i thought I would follow up.

As it stands now it allows miner to find blocks, pays the main wallet, does not send share to miner, nor does it update the front end to reflect found blocks. 

And when it does find a valid block it logs:

04/26/2018 05:00:54 -04:00 [Debug] [ShareManager] [LiteCoinPlus] We thought a block was found but it was rejected by the coin daemon; [991783c3a69ec3957995205089d3fe7c1fa91a48d98b05933e9169af5c3287dd] - reason; Block not found

**Comment by flyx2888** [comment]
@arebias 

I'll look into this problem as soon as I can. No promises I'll find anything, but if I do I'll fix it.

**Comment by arebias** [comment]
OK. In the meantime, I am flushing all redis DB's as well as dropping and creating the MYSQL DB's over again to make sure they have nothing to do with it.

Thanks

**Comment by flyx2888** [comment]
K. Do each of your coin pools have their own db's both in mysql and redis? That's what I would suggest.

**Comment by arebias** [comment]
Yes. And each coin has its own redis id i.e, 0,1,2

"storage": {
        "hybrid": {
            "enabled": true,
		    "redis": {
			    "host": "127.0.0.1",
			    "port": 6379,
                "password": "",
                "databaseId": 2
		    },
		    "mysql": {
			    "host": "127.0.0.1",
			    "port": 3306,
			    "database": "csrv",
                "user": "user",
                "password": "pass"
		    }
        },
        "mpos": {
            "enabled": false,
		    "mysql": {
			    "host": "127.0.0.1",
			    "port": 3306,
			    "user": "username",
			    "password": "password",
                "database": "db-name"
		    }
        }
	},

**Comment by flyx2888** [comment]
@arebias 

Your coin config should be the following:

{
	"name": "LiteCoinPlus",
	"symbol": "LCP",
	"algorithm": "scrypt",
	"site": "http://litecoinplus.co/",
	"blockExplorer": {
	"block": "http://lcp.altcoinwarz.com:3004/block/block.dws?",
	"tx": "http://lcp.altcoinwarz.com:3004/tx/tx.dws?",
	"address": "http://lcp.altcoinwarz.com:3004/address/address.dws?"
    },
    "options": {
        "isProofOfStakeHybrid": true
    }
}


I'm still waiting for the wallet to sync before I can begin full testing and debugging. In the meantime, get me the hash of the found block.  I searched for this hash: [991783c3a69ec3957995205089d3fe7c1fa91a48d98b05933e9169af5c3287dd], which you originally posted and was unable to find it on the block explorer.

**Comment by arebias** [comment]
[518843fe38bd1c66196535b22bb35ea8354a03c8007c825f967881af6d03a6d4](http://lcp.altcoinwarz.com/tx/518843fe38bd1c66196535b22bb35ea8354a03c8007c825f967881af6d03a6d4)

That is one of them. 

I wish this thing could find blocks faster as it would help in testing. If you use the test net how does that work? Does it mine fake blocks more often?

**** EDIT *****

Just solved another block but even with that coin configuration, it did not register. 

See anything different in RPC for this wallet than normal?

`
addmultisigaddress <nrequired> <'["key","key"]'> [account]
backupwallet <destination>
checkwallet
createrawtransaction [{"txid":txid,"vout":n},...] {address:amount,...}
decoderawtransaction <hex string>
dumpprivkey <LitecoinPlusaddress>
encryptwallet <passphrase>
getaccount <LitecoinPlusaddress>
getaccountaddress <account>
getaddressesbyaccount <account>
getbalance [account] [minconf=1]
getblock <hash> [txinfo]
getblock <number> [txinfo]
getblockcount
getblockhash <index>
getblocktemplate [params]
getcheckpoint
getconnectioncount
getdifficulty
getgenerate
gethashespersec
getinfo
getmininginfo
getnewaddress [account]
getnewpubkey [account]
getpeerinfo
getrawmempool
getrawtransaction <txid> [verbose=0]
getreceivedbyaccount <account> [minconf=1]
getreceivedbyaddress <LitecoinPlusaddress> [minconf=1]
gettransaction <txid>
getwork [data]
getworkex [data, coinbase]
help [command]
importprivkey <LitecoinPlusprivkey> [label]
keypoolrefill
listaccounts [minconf=1]
listaddressgroupings
listreceivedbyaccount [minconf=1] [includeempty=false]
listreceivedbyaddress [minconf=1] [includeempty=false]
listsinceblock [blockhash] [target-confirmations]
listtransactions [account] [count=10] [from=0]
listunspent [minconf=1] [maxconf=9999999] ["address",...]
makekeypair [prefix]
move <fromaccount> <toaccount> <amount> [minconf=1] [comment]
repairwallet
resendtx
reservebalance [<reserve> [amount]]
sendalert <message> <privatekey> <minver> <maxver> <priority> <id> [cancelupto]
sendfrom <fromaccount> <toLitecoinPlusaddress> <amount> [minconf=1] [comment] [comment-to]
sendmany <fromaccount> {address:amount,...} [minconf=1] [comment]
sendrawtransaction <hex string>
sendtoaddress <LitecoinPlusaddress> <amount> [comment] [comment-to]
setaccount <LitecoinPlusaddress> <account>
setgenerate <generate> [genproclimit]
settxfee <amount>
signmessage <LitecoinPlusaddress> <message>
signrawtransaction <hex string> [{"txid":txid,"vout":n,"scriptPubKey":hex},...] [<privatekey1>,...] [sighashtype="ALL"]
stop <detach>
submitblock <hex data> [optional-params-obj]
validateaddress <LitecoinPlusaddress>
validatepubkey <LitecoinPluspubkey>
verifymessage <LitecoinPlusaddress> <signature> <message>
-zapwallettxes

`

**Comment by arebias** [comment]
At 10:29 a block came into my wallet as solved: [000000000004bd4b22cb830f44cda0eac253485a3dbd76af71980cb9d1baf1f9](http://lcp.altcoinwarz.com/block/000000000004bd4b22cb830f44cda0eac253485a3dbd76af71980cb9d1baf1f9)

At the same time, the block was listed in the debug.log as:

04/29/2018 10:29:57 -04:00 [Debug] [ShareManager] [LiteCoinPlus] We thought a block was found but it was rejected by the coin daemon; [556b10b9d567c975c8bbc07e24db76152234557fc838770d3bda7b54f68cb352] - reason; Block not found

And of course, that block listed in the debug.log is not listed as valid on the block explorer however my wallet was credited with the coins and associated with the top listed and linked block hash. 

What would cause the block to be reported to CoiniumServ incorrectly I wonder?

**Comment by flyx2888** [comment]
@arebias 

This is the block hash: 000000000004bd4b22cb830f44cda0eac253485a3dbd76af71980cb9d1baf1f9 of the block found. And this should be the txid: e1a26b4536349318bb7e1e1c3dbfc292599ec87d544f7f1f0a62cd4cea9dfa41 of that same block, which does not match the txid of the one that's logged and thus the reason for the error exception.

I'll know more once I have the wallet synch'd and start testing. I doubt it's gonna make a difference but try this coin config rather:

{
    "name": "LiteCoinPlus",
    "symbol": "LCP",
    "algorithm": "scrypt",
    "site": "http://litecoinplus.co/",
    "blockExplorer": {
        "block": "http://lcp.altcoinwarz.com:3004/block/block.dws?",
        "tx": "http://lcp.altcoinwarz.com:3004/tx/tx.dws?",
        "address": "http://lcp.altcoinwarz.com:3004/address/address.dws?"
    },
    "options": {
		"isProofOfStakeHybrid": true,
		"blockTemplateModeRequired": true,
		"useDefaultAccount": true,
		"txMessageSupported": true,
		"SubmitBlockSupported": true	
    },
	"node": {
        "magic": "cefbfadb",
        "testnetMagic": "cdf1c0ef"
    }
}


On testnet it'll all depend on difficulty level, but technically you should find them faster since there should be less miners which will bring down the difficulty level.

**Comment by flyx2888** [comment]
@arebias 

Don't get too happy just yet, but I think I may have found the bug. Can't confirm this till I begin testing and debugging. Stay tuned.... wallet sync only at 54%.

**Comment by arebias** [comment]
No problem and no rush. 

Thank you for looking into this.

**Comment by flyx2888** [comment]
@arebias 

Can you please send me your log files? Zip all 3 into 1 zip file.

**Comment by arebias** [comment]
Sure. 

First, allow me to try another coin that I can solve blocks faster with. It will do two things:
1. Allow me to make sure it is something with CoiniumServ and not my setup (network, daemons, etc..)
2.) It will give you examples from both coins in the log.

I should be able to have a good sample of fresh logs in the morning with a few found blocks of both types of coins.

**Comment by flyx2888** [comment]
@arebias 

Perfect. Thanks for your thoroughness it will definitely help.

**Comment by arebias** [comment]
[logs.zip](https://github.com/bonesoul/CoiniumServ/files/1963321/logs.zip)

I found two blocks on the LCP but it turns out the other wallet I was going to use and thought would be faster has some issues.

**Comment by arebias** [comment]
I will add this screenshot of using BFGMiner instead of CGMiner (L3+) and connecting via stratum. 

Notice "(all pools are dead" in the top left corner of the BFGMiner as well as the error that is thrown in CoiniumServ. SocketException on ReceiveCallback 

![error_bfgminer](https://user-images.githubusercontent.com/5103145/39468209-e908384a-4cff-11e8-964a-46ba1745864e.jpg)

**Comment by jeong760** [comment]
@arebias 

Please try this coin.json info. I think the blockchain info address is incorrect, that's why CoiniumServ does not get proper information from blockchain explorer website of Litecoin plus.

litecoinplus.json

{
     "name": "LiteCoinPlus",
     "symbol": "LCP",
     "algorithm": "scrypt",
     "site": "http://litecoinplus.co/",
    "blockExplorer": {
             "block": "http://lcp.altcoinwarz.com:3004/block/",
             "tx": "http://lcp.altcoinwarz.com:3004/tx/",
             "address": "http://lcp.altcoinwarz.com:3004/address/"
      }
}

**Comment by flyx2888** [comment]
@arebias 

It wass incorrect. I noticed it the other day but forgot to tell you. Use this rather, wgich i've edited on my end already:

{
    "name": "Litecoin Plus",
    "symbol": "LCP",
    "algorithm": "scrypt",
    "site": "http://litecoinplus.co/",
    "blockExplorer": {
        "block": "http://lcp.altcoinwarz.com/block/",
        "tx": "http://lcp.altcoinwarz.com/tx/",
        "address": "http://lcp.altcoinwarz.com/address/"
    },
    "options": {
	"isProofOfStakeHybrid": true
    },
    "node": {
        "magic": "cefbfadb",
	"testnetMagic": "cdf1c0ef"
    }
}

**Comment by flyx2888** [comment]
@arebias 

The receive callback error, I've noticed happens occasionally with some coins but not all. It's non-fatal and self recovers so I haven't made it a priority to determine the cause yet.

Please post your startup cmd string or batch file (if using one) for BFGMiner.

**Comment by arebias** [comment]
OK. I read that earlier and made the changes but I have yet to hit a block since 8:48 am otherwise I would have come in and let you know that I got the post and was trying it out. 

This morning I was hitting a block about every 20 to 30 minutes and then, nada!

What I did find surprising about the changes that you had made was the fact that CoiniumServ relies on the block explorer to substantiate a blocks validity. I thought for sure that was all done by the wallet interaction with the blockchain. 

Learning many new things.

**Comment by arebias** [comment]
I only use the BFGMiner for these small USB ASIC's when testing something out so it is not that often. But here is the command line in the batch file I was using today to mine through CoiniumServ. 

bfgminer.exe --scrypt -o stratum+tcp://192.168.254.4:3332 -u XM4ksugtkGkoaAWzFY151zeCfSzraHR5ZR -p x -S MLD:all --set MLD:clock=600

Also, I might add that the BFGMiner is a modified version.

**Comment by flyx2888** [comment]
@arebias 

Yea it does. Many of those coin config files are outdated and needs to be updated. Block explorers comes and goes as do the coin websites. For those unknowing, they will simply use the file as is without ever modifying them.

Okay, here's 1 thing I noticed and thus asked for your startup cmd string... on Antminers, I've often seen them not connecting when specifying stratum+tcp://192.168.254.4:3332. The server appears dead to them. But if you specify 192.168.254.4:3332 only for the URL then they work perfectly. I wonder if the problem is similar for other software based miners.

**Comment by arebias** [comment]
Well, the Antminer is running CGMiner and it doesn't seem to phase it from what I have seen. 

I must have done something wrong today though since I have not solved a block since this morning. Something is not right. 

Did you say that you used that coin definition using Litecoin Plus and it worked for you?

**Comment by flyx2888** [comment]
@arebias 

Older antminer's use CGMiner. New antminer's use BMMiner, which does seem to be a problem.

Yes, that coin config I posted  is working properly.

**Comment by arebias** [comment]
I think I have one older one and one newer one but as I am checking the running processes right now I can see that they are both running CGMiner.

I have made the changes (all that you suggested including eliminating the stratum part) and started everything back up. I should know within an hour or so if it is working.

BTW; do you have daemon=1 in your wallet config?

**Comment by flyx2888** [comment]
@arebias 

rpcuser=user
rpcpassword=pass
rpcallowip=127.0.0.1
rpcallowip=10.0.1.0/24
rpcport=44350
algo=scrypt
gen=0
staking=1
daemon=1
server=1
listen=1

addnode=65.102.140.117
addnode=65.102.140.115
addnode=5.189.137.226
addnode=198.23.219.66
addnode=217.175.119.125
addnode=192.168.0.76
addnode=94.130.14.168

**Comment by flyx2888** [comment]
@arebias 

Yours should have this instead:

rpcallowip=127.0.0.1
rpcallowip=192.168.254.0/24

**Comment by arebias** [comment]
@flyx2888
Let me have your LCP address, please.

**Comment by flyx2888** [comment]
@arebias 

XHEQE5siYuF5uNximEB4CB2uUFfEKBGvhs

**Comment by flyx2888** [comment]
@arebias 

Thank you very much. It's very generous of you and much appreciated. My very first bit of LCP  :) as I don't mine this coin.

**Comment by arebias** [comment]
@flyx2888

You are more than welcome. I don't know if I have it fixed yet but you have given so much time already that is just something for you to stake. Keep your wallet open and it will add to it over time. 15% they say.

Came through pretty fast I would imagine. It does for me.

**Comment by flyx2888** [comment]
@arebias 

Yes, it came through about 30 secs. after I sent you the address. I'll keep it staking and will help you as much as necessary to resolve this issue. I don't have such issues because I use this server to solo so everything comes to me regardless, but I don't like seeing bugs. If I find them, I will fix them because I can. :)

**Comment by arebias** [comment]
@flyx2888 

Well, nothing has worked and still only enters into the database "account" and "versioninfo" and fails to enter "block", "payment", and "transaction" entries so I would assume it has something more to do with my particular Redis and MySQL setup and how it interacts or fails to interact properly with CoiniumServ.

Either way, I think you have eliminated the possibility of there being a 'bug' in the code so I will close and maybe one day decide to give it another go. 

Thanks for all the help and time.

**Comment by flyx2888** [comment]
@arebias 

There's no need to give up now. We can continue to figure out other possible causes. What version Redis and MySQL are you using? And the most obvious, what version CoiniumServ?

**Comment by flyx2888** [comment]
@arebias 

I'm confident you can get this working. Maleksh, another user on this site have been at it for over 2 months and couldn't get it working himself. I finally stepped in last week and setup a server for him and it's now running smoothly.

**Comment by crusher72** [comment]
There's nothing wrong here, except for the block explorer. A few coins I have tried to set up from that block explorer fail, all other coins on numerous algorithms including even NYAN coin work lol

**Comment by arebias** [comment]
@flyx2888 

I am not giving up entirely. After I closed the issue I immediately began exploring the Redis and MySQL portion of the setup. I just didn't see any reason to keep the "issue" open and cluttering up the real purpose of the section which is to address bugs in CoiniumServ. Since I feel confident that the actual 'bug' is with my personal setup I can address that.

As far as versions - that might be where the problem lies. 

MySQL Server 5.7.21 
Redis on Windows 4.0.2
CoiniumServ 0.2.6.3

**Comment by flyx2888** [comment]
Use a different block explorer then. There are others, easily solved.

**Comment by flyx2888** [comment]
@arebias 

Contact me directly. Let's get this working for you.  flyx2888 at yahoo dot com.

Send me your pool conf file and your redis.conf file.

Don't worry about cluttering up this section, there are plenty of non-bug related issues here. You need help so let's just get this working.

**Comment by arebias** [comment]
@flyx2888 
I am going to tear down my system install of Node.js and NPM as well as other stuff that I think is actually causing the underlying problems with not only this but other stuff as well. If I get everything back up and situated I will let you know how I am coming.

@crusher72 
I did try your suggestion but to no avail, however, I think the underlying problem is a bit deeper. For one thing, I can't understand for the life of me how the CoiniumServ software can be coded to rely solely on a block explorer external to the local wallet and the reason I question that is because unless I am mistaken, doesn't any install of any block explorer software rely on their individual install of a wallet? 

It would seem a waste of time to rely on information reported elsewhere when that info is exactly the same kind of info that is available to my own individual wallet. 

Either way, it does not matter. I briefly looked for the constructor in the code for utilizing the coin.json addresses for 1, to see exactly what they were appending to and where and 2, hoping to find why on earth CS would call the info externally for validation but I don't have the motivation I had back when I was younger and could think much clearer.

**Comment by flyx2888** [comment]
@arebias 

Okay, do let me know. When you get to that point I can walk you through it step-by-step if need be.
