### ISSUE TITLE
issue while compiling

### ISSUE THREAD

**Issue by xborow** [bonesoul/CoiniumServ#1028]
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 5/15/2018 10:04:51 AM.
__________________________________________________
/home/temp/Downloads/CoiniumServ/CoiniumServ.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.
Project "/home/temp/Downloads/CoiniumServ/CoiniumServ.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Release|Any CPU".
	Target Build:
		Project "/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
			Target GetFrameworkPaths:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.7' not supported by this toolset (ToolsVersion: 14.0).
			Target GetReferenceAssemblyPaths:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.7'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
			Target _GenerateTargetFrameworkMonikerAttribute:
			Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
			Target CoreCompile:
				Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug- /optimize+ /out:obj/Release/CoiniumServ.exe Accounts/Account.cs Accounts/AccountManager.cs Accounts/IAccount.cs Accounts/IAccountManager.cs Algorithms/AlgorithmManager.cs Algorithms/AlgorithmRegistry.cs Algorithms/HashAlgorithmStatistics.cs Algorithms/IAlgorithmManager.cs Algorithms/IHashAlgorithm.cs Algorithms/IHashAlgorithmStatistics.cs Algorithms/Implementations/Blake.cs Algorithms/Implementations/C11.cs Algorithms/Implementations/Fresh.cs Algorithms/Implementations/Fugue.cs Algorithms/Implementations/Groestl.cs Algorithms/Implementations/Keccak.cs Algorithms/Implementations/Nist5.cs Algorithms/Implementations/Qubit.cs Algorithms/Implementations/Scrypt.cs Algorithms/Implementations/ScryptN.cs Algorithms/Implementations/ScryptOg.cs Algorithms/Implementations/Sha1.cs Algorithms/Implementations/Sha256.cs Algorithms/Implementations/Shavite3.cs Algorithms/Implementations/Skein.cs Algorithms/Implementations/X11.cs Algorithms/Implementations/X13.cs Algorithms/Implementations/X14.cs Algorithms/Implementations/X15.cs Algorithms/Implementations/X16r.cs Algorithms/Implementations/X17.cs Banning/BanConfig.cs Banning/BanManager.cs Banning/IBanConfig.cs Banning/IBanManager.cs Blocks/BlockProcessor.cs Blocks/IBlockProcessor.cs Coin/Address/Base58.cs Coin/Address/Exceptions/AddressFormatException.cs Coin/Address/Exceptions/AddressNotOwnedException.cs Coin/Address/Exceptions/InvalidWalletAddressException.cs Coin/Coinbase/Serializers.cs Coin/Coinbase/Utils.cs Coin/Config/BlockExplorerOptions.cs Coin/Config/CoinConfig.cs Coin/Config/CoinOptions.cs Coin/Config/IBlockExplorerOptions.cs Coin/Config/ICoinConfig.cs Coin/Config/ICoinOptions.cs Configuration/ConfigFactory.cs Configuration/ConfigManager.cs Configuration/IConfig.cs Configuration/IConfigFactory.cs Configuration/IConfigManager.cs Configuration/IJsonConfigReader.cs Configuration/JsonConfigReader.cs Container/Bootstrapper.cs Container/Context/ApplicationContext.cs Container/Context/IApplicationContext.cs Container/IObjectFactory.cs Container/ObjectFactory.cs Container/Registries/ClassRegistry.cs Container/Registries/FactoryRegistry.cs Container/Registries/IRegistry.cs Container/Registries/ManagerRegistry.cs Container/Registries/Registry.cs Container/Registries/ServerRegistry.cs Container/Registries/StorageRegistry.cs Cryptology/Hash.cs Cryptology/Merkle/IMerkleTree.cs Cryptology/Merkle/MerkleTree.cs Cryptology/Utils.cs Daemon/Config/DaemonConfig.cs Daemon/Config/IDaemonConfig.cs Daemon/Converters/DifficultyConverter.cs Daemon/Converters/PropertyConverter.cs Daemon/Converters/TimeConverter.cs Daemon/DaemonBase.cs Daemon/DaemonClient.cs Daemon/DaemonManager.cs Daemon/DaemonRequest.cs Daemon/DaemonResponse.cs Daemon/Errors/RpcError.cs Daemon/Errors/RpcErrorCode.cs Daemon/Errors/RpcErrorResponse.cs Daemon/Exceptions/IRpcExceptionFactory.cs Daemon/Exceptions/RpcConnectionException.cs Daemon/Exceptions/RpcErrorException.cs Daemon/Exceptions/RpcException.cs Daemon/Exceptions/RpcExceptionFactory.cs Daemon/Exceptions/RpcTimeoutException.cs Daemon/IDaemonBase.cs Daemon/IDaemonClient.cs Daemon/IDaemonManager.cs Daemon/Requests/CreateRawTransaction.cs Daemon/Requests/CreateRawTransactionInput.cs Daemon/Requests/SignRawTransaction.cs Daemon/Requests/SignRawTransactionInput.cs Daemon/Responses/AddedNodeInfo.cs Daemon/Responses/Block.cs Daemon/Responses/BlockTemplate.cs Daemon/Responses/BlockTemplateTransaction.cs Daemon/Responses/DecodedRawTransaction.cs Daemon/Responses/GetAddressInfo.cs Daemon/Responses/Getwork.cs Daemon/Responses/IBlockTemplate.cs Daemon/Responses/Info.cs Daemon/Responses/ListReceivedByAccountTransaction.cs Daemon/Responses/ListReceivedByAddressTransaction.cs Daemon/Responses/ListTransaction.cs Daemon/Responses/MiningInfo.cs Daemon/Responses/MultisigAddress.cs Daemon/Responses/NodeAddress.cs Daemon/Responses/PeerInfo.cs Daemon/Responses/SignedRawTransaction.cs Daemon/Responses/Transaction.cs Daemon/Responses/TransactionDetail.cs Daemon/Responses/TransactionSinceBlock.cs Daemon/Responses/TransactionsSinceBlock.cs Daemon/Responses/TxOutSetInfo.cs Daemon/Responses/UnspentTransaction.cs Daemon/Responses/ValidateAddress.cs Jobs/ExtraNonce.cs Jobs/IExtraNonce.cs Jobs/IJob.cs Jobs/IJobCounter.cs Jobs/Job.cs Jobs/JobCounter.cs Jobs/Manager/IJobConfig.cs Jobs/Manager/IJobManager.cs Jobs/Manager/JobConfig.cs Jobs/Manager/JobManager.cs Jobs/Tracker/IJobTracker.cs Jobs/Tracker/JobTracker.cs Logging/ILogConfig.cs Logging/ILogManager.cs Logging/ILogTarget.cs Logging/LogConfig.cs Logging/LogManager.cs Logging/LogTarget.cs Mining/IMetaConfig.cs Mining/IMiner.cs Mining/IMinerConfig.cs Mining/IMinerManager.cs Mining/MetaConfig.cs Mining/MinerConfig.cs Mining/MinerEventArgs.cs Mining/MinerManager.cs Mining/MinerSoftware.cs Mining/Software/IMiningSoftware.cs Mining/Software/IMiningSoftwareConfig.cs Mining/Software/ISoftwareRepository.cs Mining/Software/ISoftwareRepositoryConfig.cs Mining/Software/MiningSoftware.cs Mining/Software/MiningSoftwareConfig.cs Mining/Software/SoftwareRepository.cs Mining/Software/SoftwareRepositoryConfig.cs Payments/BlockAccounter.cs Payments/Config/IPaymentConfig.cs Payments/Config/IRewardsConfig.cs Payments/Config/IWalletConfig.cs Payments/Config/PaymentConfig.cs Payments/Config/RewardsConfig.cs Payments/Config/WalletConfig.cs Payments/IBlockAccounter.cs Payments/IPayment.cs Payments/IPaymentDetails.cs Payments/IPaymentLabor.cs Payments/IPaymentManager.cs Payments/IPaymentProcessor.cs Payments/IPaymentRepository.cs Payments/IPaymentRound.cs Payments/ITransaction.cs Payments/Payment.cs Payments/PaymentDetails.cs Payments/PaymentManager.cs Payments/PaymentProcessor.cs Payments/PaymentRepository.cs Payments/PaymentRound.cs Payments/Transaction.cs Persistance/Blocks/BlockStatus.cs Persistance/Blocks/IPersistedBlock.cs Persistance/Blocks/PersistedBlock.cs Persistance/IStorageConfig.cs Persistance/Layers/Hybrid/HybridStorage.Accounts.cs Persistance/Layers/Hybrid/HybridStorage.Blocks.cs Persistance/Layers/Hybrid/HybridStorage.cs Persistance/Layers/Hybrid/HybridStorage.Miners.cs Persistance/Layers/Hybrid/HybridStorage.Payments.cs Persistance/Layers/Hybrid/HybridStorage.Shares.cs Persistance/Layers/Hybrid/HybridStorage.Statistics.cs Persistance/Layers/Hybrid/HybridStorageConfig.cs Persistance/Layers/Hybrid/IMigrationManager.cs Persistance/Layers/Hybrid/MigrationManager.cs Persistance/Layers/Hybrid/Migrations/M001CreateBlocksTable.cs Persistance/Layers/Hybrid/Migrations/M002Payments.cs Persistance/Layers/Hybrid/Migrations/M003FixDefaults.cs Persistance/Layers/IStorageLayer.cs Persistance/Layers/IStorageLayerConfig.cs Persistance/Layers/Mpos/MposStorage.Accounts.cs Persistance/Layers/Mpos/MposStorage.Blocks.cs Persistance/Layers/Mpos/MposStorage.cs Persistance/Layers/Mpos/MposStorage.Miners.cs Persistance/Layers/Mpos/MposStorage.Payments.cs Persistance/Layers/Mpos/MposStorage.Shares.cs Persistance/Layers/Mpos/MposStorage.Statistics.cs Persistance/Layers/Mpos/MposStorageConfig.cs Persistance/Layers/Null/NullStorage.cs Persistance/Layers/Null/NullStorageConfig.cs Persistance/Layers/StorageLayers.cs Persistance/Providers/IStorageProvider.cs Persistance/Providers/IStorageProviderConfig.cs Persistance/Providers/MySql/IMySqlProvider.cs Persistance/Providers/MySql/IMySqlProviderConfig.cs Persistance/Providers/MySql/MySqlProvider.cs Persistance/Providers/MySql/MySqlProviderConfig.cs Persistance/Providers/Redis/IRedisProvider.cs Persistance/Providers/Redis/IRedisProviderConfig.cs Persistance/Providers/Redis/RedisClient.cs Persistance/Providers/Redis/RedisProvider.cs Persistance/Providers/Redis/RedisProviderConfig.cs Persistance/Providers/StorageProviders.cs Persistance/Query/IPaginationQuery.cs Persistance/Query/PaginationQuery.cs Persistance/StorageConfig.cs Pools/BlocksRepository.cs Pools/IBlockRepository.cs Pools/INetworkInfo.cs Pools/IPool.cs Pools/IPoolConfig.cs Pools/IPoolManager.cs Pools/NetworkInfo.cs Pools/Pool.cs Pools/PoolConfig.cs Pools/PoolManager.cs Program.cs Properties/AssemblyInfo.cs Server/Commands/Server.cs Server/Commands/Stats.cs Server/Commands/Uptime.cs Server/Commands/Version.cs Server/IServer.cs Server/IServerConfig.cs Server/Mining/Getwork/GetworkContext.cs Server/Mining/Getwork/GetworkMiner.cs Server/Mining/Getwork/GetworkServer.cs Server/Mining/Getwork/GetworkServerConfig.cs Server/Mining/Getwork/GetworkService.cs Server/Mining/Getwork/HttpServer.cs Server/Mining/Getwork/IGetworkMiner.cs Server/Mining/Getwork/IGetworkServerConfig.cs Server/Mining/IMiningServer.cs Server/Mining/Service/IRpcService.cs Server/Mining/Service/Services.cs Server/Mining/Stratum/Errors/AuthenticationError.cs Server/Mining/Stratum/Errors/DuplicateShareError.cs Server/Mining/Stratum/Errors/IStratumError.cs Server/Mining/Stratum/Errors/JobNotFoundError.cs Server/Mining/Stratum/Errors/LowDifficultyShare.cs Server/Mining/Stratum/Errors/NotSubscriberError.cs Server/Mining/Stratum/Errors/OtherError.cs Server/Mining/Stratum/IStratumMiner.cs Server/Mining/Stratum/IStratumServerConfig.cs Server/Mining/Stratum/Responses/SubscribeResponse.cs Server/Mining/Stratum/Sockets/BannedConnectionEventArgs.cs Server/Mining/Stratum/Sockets/Connection.cs Server/Mining/Stratum/Sockets/ConnectionDataEventArgs.cs Server/Mining/Stratum/Sockets/ConnectionEventArgs.cs Server/Mining/Stratum/Sockets/IClient.cs Server/Mining/Stratum/Sockets/IConnection.cs Server/Mining/Stratum/Sockets/ISocketServer.cs Server/Mining/Stratum/Sockets/SocketServer.cs Server/Mining/Stratum/StratumContext.cs Server/Mining/Stratum/StratumMiner.cs Server/Mining/Stratum/StratumServer.cs Server/Mining/Stratum/StratumServerConfig.cs Server/Mining/Stratum/StratumService.cs Server/Stack/IStackConfig.cs Server/Stack/IStackNode.cs Server/Stack/StackConfig.cs Server/Stack/StackNode.cs Server/Web/Config/BackendConfig.cs Server/Web/Config/IBackendConfig.cs Server/Web/Config/IWebServerConfig.cs Server/Web/Config/WebServerConfig.cs Server/Web/ErrorConfiguration.cs Server/Web/IWebServer.cs Server/Web/Models/Algorithm/AlgorithmModel.cs Server/Web/Models/Algorithm/AlgorithmsModel.cs Server/Web/Models/ApiModel.cs Server/Web/Models/GettingStarted/GettingStartedModel.cs Server/Web/Models/GettingStarted/GettingStartedPoolModel.cs Server/Web/Models/IndexModel.cs Server/Web/Models/JsonError.cs Server/Web/Models/Pool/AccountModel.cs Server/Web/Models/Pool/BlockModel.cs Server/Web/Models/Pool/BlocksModel.cs Server/Web/Models/Pool/PaymentDetailsModel.cs Server/Web/Models/Pool/PoolModel.cs Server/Web/Models/Pool/PoolsModel.cs Server/Web/Models/RoundModel.cs Server/Web/Models/WorkersModel.cs Server/Web/Modules/AlgorithmModule.cs Server/Web/Modules/AlgorithmsModule.cs Server/Web/Modules/ApiModule.cs Server/Web/Modules/ContactModule.cs Server/Web/Modules/DonateModule.cs Server/Web/Modules/HelpModule.cs Server/Web/Modules/IndexModule.cs Server/Web/Modules/PoolModule.cs Server/Web/Modules/PoolsModule.cs Server/Web/Modules/TosModule.cs Server/Web/NancyBootstrapper.cs Server/Web/RootPathProvider.cs Server/Web/Service/IJsonService.cs Server/Web/WebServer.cs Shares/IShare.cs Shares/IShareManager.cs Shares/Share.cs Shares/ShareError.cs Shares/ShareEventArgs.cs Shares/ShareManager.cs Statistics/IStatisticsConfig.cs Statistics/IStatisticsManager.cs Statistics/StatisticsConfig.cs Statistics/StatisticsManager.cs Transactions/GenerationTransaction.cs Transactions/IGenerationTransaction.cs Transactions/IOutputs.cs Transactions/OutPoint.cs Transactions/Outputs.cs Transactions/Script/ISignatureScript.cs Transactions/Script/SignatureScript.cs Transactions/TxIn.cs Transactions/TxOut.cs Transactions/Utils/TransactionUtils.cs Utils/Buffers/IRingBuffer.cs Utils/Buffers/RingBuffer.cs Utils/Commands/CommandAttributes.cs Utils/Commands/CommandGroup.cs Utils/Commands/CommandManager.cs Utils/ConsoleWindow.cs Utils/Extensions/ArrayExtensions.cs Utils/Extensions/EnumerableExtensions.cs Utils/Extensions/JsonExtensions.cs Utils/Extensions/LinqExtensions.cs Utils/Extensions/StringExtensions.cs Utils/Helpers/Amount.cs Utils/Helpers/ArrayHelpers.cs Utils/Helpers/Enforce.cs Utils/Helpers/FileHelpers.cs Utils/Helpers/Humanize.cs Utils/Helpers/Range.cs Utils/Helpers/TimeHelpers.cs Utils/Numerics/BigInteger.cs Utils/Numerics/BigRational.cs Utils/Platform/Frameworks.cs Utils/Platform/PlatformManager.cs Utils/Repository/IRepository.cs Vardiff/IVardiffConfig.cs Vardiff/IVardiffManager.cs Vardiff/IVardiffMiner.cs Vardiff/VardiffConfig.cs Vardiff/VardiffManager.cs VersionInfo.cs obj/Release/.NETFramework,Version=v4.7.AssemblyAttribute.cs /target:exe /define:TRACE /nostdlib /platform:AnyCPU /reference:../../packages/AustinHarris.JsonRpc.1.1.70/lib/net40/AustinHarris.JsonRpc.dll /reference:../../packages/BouncyCastle.1.8.1/lib/BouncyCastle.Crypto.dll /reference:../../packages/CryptSharpOfficial.2.1.0.0/lib/CryptSharp.dll /reference:../../packages/Dapper.1.50.4/lib/net451/Dapper.dll /reference:../../packages/FluentMigrator.1.6.2/lib/40/FluentMigrator.dll /reference:../../packages/FluentMigrator.Runner.1.6.2/lib/40/FluentMigrator.Runner.dll /reference:../../packages/Gibbed.IO.1.0.0/lib/Gibbed.IO.dll /reference:../../packages/HashLib.2.0.1/lib/net40/HashLib.dll /reference:../../packages/JsonConfig.1.0.0/lib/JsonConfig.dll /reference:../../packages/JsonFx.2.0.1209.2802/lib/net40/JsonFx.dll /reference:../../packages/MySql.Data.6.8.8/lib/net45/MySql.Data.dll /reference:../../packages/Nancy.1.4.4/lib/net40/Nancy.dll /reference:../../packages/Nancy.CustomErrors.1.2.0.0/lib/net40/Nancy.CustomErrors.dll /reference:../../packages/Nancy.Hosting.Self.1.4.1/lib/net40/Nancy.Hosting.Self.dll /reference:../../packages/Nancy.Viewengines.Razor.1.4.3/lib/net40/Nancy.ViewEngines.Razor.dll /reference:../../packages/Newtonsoft.Json.11.0.1/lib/net45/Newtonsoft.Json.dll /reference:../../packages/Serilog.2.6.0/lib/net46/Serilog.dll /reference:../../packages/Serilog.Sinks.ColoredConsole.3.0.1/lib/net45/Serilog.Sinks.ColoredConsole.dll /reference:../../packages/Serilog.Sinks.Console.3.1.1/lib/net45/Serilog.Sinks.Console.dll /reference:../../packages/Serilog.Sinks.File.4.0.0/lib/net45/Serilog.Sinks.File.dll /reference:../../packages/Serilog.Sinks.RollingFile.3.3.0/lib/net45/Serilog.Sinks.RollingFile.dll /reference:../../packages/StackExchange.Redis.1.2.4/lib/net46/StackExchange.Redis.dll /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.IO.Compression/4.0.0.0__b77a5c561934e089/System.IO.Compression.dll /reference:../../packages/Microsoft.AspNet.Razor.3.2.4/lib/net45/System.Web.Razor.dll /reference:/usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll /reference:/usr/lib/mono/gac/System.Data.DataSetExtensions/4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll /reference:/usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll /reference:/usr/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
Pools/NetworkInfo.cs(210,44): error CS1644: Feature `type pattern matching' cannot be used because it is not part of the C# 6.0 language specification
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
		Done building project "/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/temp/Downloads/CoiniumServ/CoiniumServ.sln".-- FAILED
Done building project "/home/temp/Downloads/CoiniumServ/CoiniumServ.sln".-- FAILED

Build FAILED.

Warnings:

/home/temp/Downloads/CoiniumServ/CoiniumServ.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.

/home/temp/Downloads/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetFrameworkPaths target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.7' not supported by this toolset (ToolsVersion: 14.0).

/home/temp/Downloads/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.7'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Errors:

/home/temp/Downloads/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/Downloads/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Pools/NetworkInfo.cs(210,44): error CS1644: Feature `type pattern matching' cannot be used because it is not part of the C# 6.0 language specification

	 3 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:01.0892140

really approciate any help

**Comment by xborow** [comment]
running Kali Linux 2018.1

**Comment by xborow** [comment]
've tried to load ubuntu 18, the same issue:

Build FAILED.

Warnings:

/home/temp/CoiniumServ/CoiniumServ.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.

/home/temp/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetFrameworkPaths target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.7' not supported by this toolset (ToolsVersion: 14.0).

/home/temp/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.7'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Errors:

/home/temp/CoiniumServ/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/temp/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Pools/NetworkInfo.cs(210,44): error CS1644: Feature `type pattern matching' cannot be used because it is not part of the C# 6.0 language specification

	 3 Warning(s)
	 1 Error(s)

any help please?

**Comment by JBaczuk** [comment]
Have you followed instructions to install mono here?

[http://www.mono-project.com/download/stable/#download-lin]()

**Comment by xborow** [comment]
JBaczuk -many thanks, your comment solved the issue :+1:

**Comment by JBaczuk** [comment]
@xborow glad you could get it compiled.  Is it working for you?  I'm trying it on Ubuntu 16.04 and it runs, but doesn't seem to read my config files.  Could you send my your build by chance?
