### ISSUE TITLE
Linux compiled ver please?

### ISSUE THREAD

**Issue by xborow** [bonesoul/CoiniumServ#1029]
Seems it's not possible to compile whatewer linux i try, i would like to kindly ask to get compiled linux package, anyone please?

**Comment by xborow** [comment]
there is not available linux complied version, there is available only windows complied version for buying which is also available for free

**Comment by JBaczuk** [comment]
What errors are you getting?

**Comment by BenKnigge** [comment]
@xborow how much is this worth to you? I've got it working under ubuntu 16.04 with some minor modifications.

**Comment by xborow** [comment]
following steps within mono official webpage solved the issue, thanks to JBaczuk
