### ISSUE TITLE
Bitcoin] Error getting account for pool central wallet address

### ISSUE THREAD

**Issue by Mentors4EDU** [bonesoul/CoiniumServ#1069]
Hi, keep running to the same error while having the Bitcoin-QT daemon open on version 15.0. I see many results online for people having the same error, but no results on how to fix it. Any suggestions?

`15:05:53 [Information] [PlatformManager] [global] Running over Mono 5.14.0.177 (tarball Mon Aug  6 09:13:43 UTC 2018), framework: 4.5 (v4.0.30319.42000).
15:05:54 [Error] [StorageConfig] [global] Storage will be not working as no valid storage configuration was found!
15:05:54 [Error] [ShareManager] [Bitcoin] Error getting account for pool central wallet address: 1D2ZrZNe3JUo9ZycKCZQQaQBWd3y54F1XX - Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Information] [BanManager] [Bitcoin] No expired bans found to be cleared [remaining bans: 0].
15:05:54 [Error] [JobManager] [Bitcoin] New job creation failed: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [JobManager] [Bitcoin] New job creation failed: The request was aborted: The request was canceled.
15:05:54 [Error] [JobManager] [Bitcoin] New job creation failed: The request was aborted: The request was canceled.
15:05:54 [Error] [BlockProcessor] [Bitcoin] Error getting account for pool central wallet address: 1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX - The request was aborted: The request was canceled.
15:05:54 [Error] [PaymentProcessor] [Bitcoin] Halted as we can not connect to configured coin daemon: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [NetworkInfo] [Bitcoin] Can not read getdifficulty(): Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [NetworkInfo] [Bitcoin] Can not probe submitblock() support: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [NetworkInfo] [Bitcoin] Can not read getinfo(): Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [NetworkInfo] [Bitcoin] Can not read getmininginfo(): Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Error] [NetworkInfo] [Bitcoin] Can not read getblocktemplate(): Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:05:54 [Information] [NetworkInfo] [Bitcoin] symbol: BTC algorithm: sha256 version: null protocol: 0 wallet: 0 network difficulty: 0.00000000 block difficulty: 0.00 network hashrate: 0.00 KH/s network: mainnet peers: 0 blocks: -2 errors: none 
15:05:54 [Information] [StratumServer] [Bitcoin] Stratum server listening on 0.0.0.0:3333
15:05:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:05:55 [Information] [WebServer] [global] Web-server listening on: http://localhost/
15:06:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:07:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:08:54 [Error] [JobManager] [Bitcoin] New job creation failed: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:08:54 [Error] [JobManager] [Bitcoin] New job creation failed: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:08:54 [Error] [JobManager] [Bitcoin] New job creation failed: The request was aborted: The request was canceled.
15:08:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:09:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:10:54 [Information] [BanManager] [Bitcoin] No expired bans found to be cleared [remaining bans: 0].
15:10:54 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
15:11:54 [Error] [JobManager] [Bitcoin] New job creation failed: Error getting response stream (ReadDoneAsync2): ReceiveFailure
15:11:54 [Error] [JobManager] [Bitcoin] New job creation failed: The request was aborted: The request was canceled`

**Comment by Mentors4EDU** [comment]
Fixed, for the bitcoin config file use the RPC Port instead of the regular bind port. Then it should load up the central pool address

**Comment by parkhanju** [comment]
@Mentors4EDU I'm having the same problem. Could you tell me more about how you fixed it?

**Comment by Mentors4EDU** [comment]
> @Mentors4EDU I'm having the same problem. Could you tell me more about how you fixed it?

What I did was go to the bitcoin.conf file and use the RPC port configured on that file for the port in the json config file for bitcoin. Reran it and that fixed the problem, but I still had a few other errors when I tried hashing on the pool.
