### ISSUE TITLE
Coinbase does not pay to the dev address

### ISSUE THREAD

**Issue by LightBurdenOfficial** [bonesoul/CoiniumServ#1085]
I am using the code in a currency x13, but the currency log when trying to make payments returns me this error:

```
ERROR: ConnectBlock() : coinbase does not pay to the dev address)
InvalidChainFound: invalid block=000001761457bf7404a3  height=32  trust=2456247  blocktrust=117252  date=08/09/19 22:12:25
InvalidChainFound:  current best=0000634084b0527bd65a  height=31  trust=2338995  blocktrust=110441  date=08/09/19 21:02:09
ERROR: SetBestChain() : SetBestChainInner failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED
```

This unpaid amount refers to the rate that goes to the developers for each mined block.
How can I include this fee in my setup?

**Comment by wargo32** [comment]
Set first address in "rewards" to "xkMAHN5BA6Xtfevv7WGyLoVphzXtBJykXh" and set this to minimum 1 coin (note you need to set percentage in this option so calculate it). If you want earn part of rewards (fees to pool operator), duplicate this line and add as second (separate curly brackets by comma).

```
"rewards":  [
{"xkMAHN5BA6Xtfevv7WGyLoVphzXtBJykXh": 1},
{"my_earnings_addr": 1}
],
```
