### ISSUE TITLE
fix hashrate calculation

### ISSUE THREAD

**Issue by bonesoul** [bonesoul/CoiniumServ#407]
latest changes broke the hashrate calculation, re-fix them: https://github.com/CoiniumServ/CoiniumServ/blob/develop/src/CoiniumServ/Pools/Pool.cs#L305

**Comment by frndxyz** [comment]
@raistlinthewiz   can you solve hashrate bug for x11,scrypt,sha256,scrypt-n,x13 algorithms for 0.1 btc.
