### ISSUE TITLE
MPOS layer - hash rate reported wrong

### ISSUE THREAD

**Issue by artbatista** [bonesoul/CoiniumServ#441]
With MPOS, hash rate is reported x 6.3 actual rate reported by miner's control panel.

**Comment by jt4590** [comment]
It's a problem in AlgorithmManager.cs
The only Diff currently defined is Diff1 and DiffA DiffR and DiffS likely need to be added and defined.

**Comment by jt4590** [comment]
Edit: The code is either pulling the wrong interface data into parse, then biginteger, then diff1 (using the wrong value through the API/Interface), OR the calculation should actually be made from diffa, diffr, or diffs...

Is diff1 what normally represents the target difficulty set by the server? If so it's the right variable name, it's just pulling diffs (assuming this is the difficulty of the share from the miner) through API into the diff1 variable.

I found this post from Salfter on issue #332 and starting going through the CS files tracing it back. I'm almost to the interface layer to do some more research. (Had help from another code dev to get my head around this and I think I might be close to finding the pull through API.)

Issue #332 is actually about the Network Hash Rate while this issue #441 is about the Miner Hash Rate, but I do believe they are both really the same core issue: An incorrect pull from the interface through the API.

And the math on this checks out. It's not exactly the same as the reading Salfter is getting from his miner, but it's VERY close. The miner probably isn't showing further decimal points (or he didn't post them for simplicity), but those are being used by CoiniumServ in the full calculation.

I'm trying to use this as a replacement for stratum-mining in an MPOS installation. Looking at the entries it creates in the shares table, it writes the difficulty of the found share as reported by bfgminer, multiplied by 2^16 (I operate a Bitgem pool). stratum-mining, by comparison, writes the target difficulty (again, multiplied by 2^16). Consider this example:

[2014-10-14 12:48:23] Accepted 000dac63 GSD 0aw Diff 73m/2m

The second-to-last number (0.073) is the difficulty of a share found by my miner. The last number (0.002) is the target difficulty set by the server (this was while mining against CoiniumServ; I have it running alongside stratum-mining while I test it). CoiniumServ should write the second number (*2^16, which would probably be somewhere near 128) to the shares table. Instead, it wrote 4792.88.

**Comment by crusher72** [comment]
Any advancements on this issue?
