### ISSUE TITLE
Windows 64 bit [Error] [RedisProvider]

### ISSUE THREAD

**Issue by Kulme** [bonesoul/CoiniumServ#557]
10/12/2014 10:25:52 -04:00 [Error] [RedisProvider] [Goldcoin] An exception occured while getting version info: ERR wrong number of arguments for 'info' command
10/12/2014 10:25:52 -04:00 [Error] [RedisProvider] [Goldcoin] Redis storage initialization failed: 127.0.0.1:6379 - Value cannot be null.
Parameter name: v1

Error when I click CoiniumServ.exe

Redis Version 2.8.12
##

**Comment by computeronix** [comment]
Resolved old version of redis newest version for windows is 3.2 which works too
