### ISSUE TITLE
We thought a block was found but it was rejected by the coin daemon

### ISSUE THREAD

**Issue by Kulme** [bonesoul/CoiniumServ#571]
Error on version 0.2.2 beta
Fastcoin

On my cgminer, block found and accepted. But, CoiniumServ or fastcoind reject it and my coin reward not credited to my wallet.

10/14/2014 10:08:18 +00:00 [Debug] [ShareManager] [Fastcoin] Share accepted at 14621.44/12288 by miner fngwoNeU4pqzWsSAPABDi9UBWnW2C8hYLo
10/14/2014 10:08:20 +00:00 [Debug] [ShareManager] [Fastcoin] Share accepted at 370569.38/12288 by miner fngwoNeU4pqzWsSAPABDi9UBWnW2C8hYLo
10/14/2014 10:08:21 +00:00 [Debug] [JobTracker] [Fastcoin] Cleaned-up 3 expired jobs
10/14/2014 10:08:22 +00:00 [Error] [ShareManager] [Fastcoin] We thought a block was found but it was rejected by the coin daemon; [d84f579988d9672abc6a895e79b73f3d846707aa02000965345c1efc8f339dcd] - reason; Invalid or non-wallet transaction id
10/14/2014 10:08:29 +00:00 [Information] [BlockProcessor] [Fastcoin] No pending blocks found

**Comment by mario1987** [comment]
I have the same 

 a block was found but it was rejected by the coin daemon;

but in the wallet the block will be confirmed and also i am able to send it to an exchange.
