### ISSUE TITLE
Does anyone have an X11 pool running?

### ISSUE THREAD

**Issue by Marty19** [bonesoul/CoiniumServ#661]
Does anyone have an X11 pool running? If so, can you post config.

My X11 pools just don't seem to like any connections and keep restarting.
##

**Comment by jdghenderson** [comment]
Yes I have a cannabiscoin X11 pool running here www.coinminerz.com

I use these settings:

{
    "name": "CannabisCoin",
    "symbol": "CANN",
    "algorithm": "x11",
    "site": "http://cannabiscoin.net",
    "blockExplorer": {
        "block": "https://chainz.cryptoid.info/cann/block/",
        "tx": "https://chainz.cryptoid.info/cann/tx/",
        "address": "https://chainz.cryptoid.info/cann/address/"
    }
}



{
    "name": "CannabisCoin",
    "symbol": "CANN",
    "algorithm": "x11",
    "site": "http://cannabiscoin.net",
    "blockExplorer": {
        "block": "https://chainz.cryptoid.info/cann/block/",
        "tx": "https://chainz.cryptoid.info/cann/tx/",
        "address": "https://chainz.cryptoid.info/cann/address/"
    }
}

Thanks!

**Comment by jdghenderson** [comment]
PS - I found that only a non var diff pool with fixed difficulty of 0.001 works for X11 pools. @bonesoul is there a way we can increase the difficulty without shares being rejected for X11 coins? Thanks!

**Comment by bonesoul** [comment]
we should dig the bug then

**Comment by jdghenderson** [comment]
Okay this is what I can see in the debug when either the fixed difficulty or var diff is enabled and max is raised above 0.001:

[CoiniumServ.Shares.ShareManager] [CannabisCoin] Rejected share by miner CMHi6cYdXBsv7Q1ikmRBbzRDYcwpGjUnF3, reason: Low difficulty share of: 0.00

If I set the difficulty to 0.001 and switch off Var Diff then all shares are accepted on X11 pool but miners cannot achieve their full speed potential. For example I have a 20GHs X11 miner but it only gets small amounts of work and never gets to its full speed. The hashrate calculations are solid so no problem there. I think its just a share/difficulty issue perhaps? I tried looking at UNOMP where this supposedly works and they have a multiplier of 256 in the config for X11 coins so I tested this in a seperate build by going to X11 algorithm implementaiton but no joy either.

If you could provide guidance on where I could check next to try and fix this that would be great!

Thanks!

**Comment by jdghenderson** [comment]
Here is the full log:

11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.ShareManager] [CannabisCoin] TakeShare before share constructor: nonce=0b266d85, extranonce2=0a000000
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Entering share constructor: "0b266d85"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Jobs.Job] [Job] Share list length: 61
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Serialize Share "0b266d85"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Getting Header buffer for Share "0b266d85"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Got share "0b266d85" of length: 64
POW: 9e1f66200f0385f59a0658a6f09d839b5c554d3fdfbf296c93f648e43f00dc34fe23d78720d04e54c82ca53257edaf4bc28e639092e738d800c73d89a136ef3a
TGT:           00b797000000000000000000000000000000000000000000000000
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.ShareManager] [CannabisCoin] Rejected share by miner CMHi6cYdXBsv7Q1ikmRBbzRDYcwpGjUnF3, reason: Low difficulty share of: 0.00
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.ShareManager] [CannabisCoin] TakeShare before share constructor: nonce=0d836f23, extranonce2=08000000
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Entering share constructor: "0d836f23"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Jobs.Job] [Job] Share list length: 62
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Serialize Share "0d836f23"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Getting Header buffer for Share "0d836f23"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Got share "0d836f23" of length: 64
POW: 66867a69b73e7917e3fb4c59402d14b9bb3b725f454c9eabbca6d87ca4fc87e6a69c331e49a27feb97fe84e2dfd3cb6a07909b1e6498fbcd9d69ce393d7c0fd4
TGT:           00b797000000000000000000000000000000000000000000000000
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.ShareManager] [CannabisCoin] Rejected share by miner CMHi6cYdXBsv7Q1ikmRBbzRDYcwpGjUnF3, reason: Low difficulty share of: 0.00
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.ShareManager] [Digibyte] TakeShare before share constructor: nonce=51a5b610, extranonce2=0d000000
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Entering share constructor: "51a5b610"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Jobs.Job] [Job] Share list length: 1596
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Serialize Share "51a5b610"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Getting Header buffer for Share "51a5b610"
11/12/2017 09:06:00 +00:00 [Debug] [CoiniumServ.Shares.Share] [Share] Got share "51a5b610" of length: 32
POW: 0000005fc1ef558f5c70318ecfb720c600d19d0299c727635aa2d9c6984a154a
TGT:           0c1695000000000000000000000000000000000000000000000000

**Comment by bonesoul** [comment]
could be related to incorrect calculation of difficulty?

https://github.com/UNOMP/unified-node-open-mining-portal/blob/7b2a576644f50b2274feba386a842baf32afa7f6/libs/mposCompatibility.js#L88

**Comment by jdghenderson** [comment]
Yes it looks like it could be a biginteger issue, do i need to change something in Share.cs here:
 
// calculate the share difficulty
            Difficulty = ((double)new BigRational(AlgorithmManager.Diff1, HeaderValue)) * Job.HashAlgorithm.Multiplier;

            // calculate the block difficulty
            BlockDiffAdjusted = Job.Difficulty * Job.HashAlgorithm.Multiplier;

Or try changing the hash algorithm multiplier, as I already tried changing this value but didnt have any joy.

Thanks!

**Comment by bonesoul** [comment]
Should be multiplier but i'm not sure the value for x11.

**Comment by jdghenderson** [comment]
Yes that is what I am thinking, here is what I have found online, not sure if this correlates:

Example:

scrypt: 2^16

sha256d: 2^32

maxDiff with:

scrypt: 0x0000ffff00000000000000000000000000000000000000000000000000000000, sha256d: 0x00000000ffff0000000000000000000000000000000000000000000000000000

And X11 is:

0x00000000ffff0000000000000000000000000000000000000000000000000000
