### ISSUE TITLE
Not all Payments fullfilled

### ISSUE THREAD

**Issue by Caberhagen** [bonesoul/CoiniumServ#662]
http://s14.directupload.net/images/141028/temp/o5bn9kkm.png

in log the shares of this address all:

Share accepted at 0.00/128 by miner eWFEGMFXwPoR7PQUedVKdt6ueNJzdgVWKa

and i think its new, never see it on v0.2.3
##

**Comment by NinjaZool** [comment]
Here same problem.

My system is Debian 8.
