### ISSUE TITLE
Could not locate your error view! Details: Unable to locate view 'error'

### ISSUE THREAD

**Issue by raine0001** [bonesoul/CoiniumServ#680]
Could not locate your error view! Details: Unable to locate view 'error'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views//error-en-US,views//error,/error-en-US,/error,views/error-en-US,views/error,error-en-US,error
Root path: C:\Users\Raine\Desktop\coiniumserv-0.2.4\web\default
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'

Windows 7
Redis 2.8.12 64 bit
node.js 0.10.32
##

**Comment by sologap** [comment]
i'm having the same issue i paid for that :( : 

Could not locate your error view! Details: Unable to locate view 'error'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views//error-en-US,views//error,/error-en-US,/error,views/error-en-US,views/error,error-en-US,error
Root path: C:\Users\X\Desktop\CoiniumServ-0.2.4-beta\web\default
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
