### ISSUE TITLE
JouleCoin issue

### ISSUE THREAD

**Issue by Marty19** [bonesoul/CoiniumServ#682]
Could you please explain what this message means:

10/30/2014 12:25:30 +00:00 [Debug] [ShareManager] [Joulecoin] We thought a block was found but it was rejected by the coin daemon; [9524a036fdc6cb2c07545df5adedbda0bff6836c7daebd88a88a7c5042fd5ac6] - reason; Block decode failed

I am getting it on my JouleCoin pool.

Thanks
##

**Comment by jdghenderson** [comment]
To confirm I am mining Joulecoin on the latest version and it works fine:

{
    "name": "Joulecoin",
    "symbol": "XJO",
    "algorithm": "sha256",
    "site": "http://www.jouleco.in/",
    "blockExplorer": {
        "block": "https://chainz.cryptoid.info/xjo/block.dws?",
        "tx": "https://chainz.cryptoid.info/xjo/tx.dws?",
        "address": "https://chainz.cryptoid.info/xjo/address.dws?"
     },
    "options": {
        "isProofOfStakeHybrid": false,
        "blockTemplateModeRequired": false,
        "useDefaultAccount": false,
        "txMessageSupported": true        
    }
}

Thanks!
