### ISSUE TITLE
End Users are unable to connect

### ISSUE THREAD

**Issue by agentsmith5443** [bonesoul/CoiniumServ#706]
End Users are unable to connect.

http://respectfreedom.com

Can someone test this?

Notice: Pool verificator is still in BETA. It may contain some bugs and it may report pool being compatible while in fact it is not compatible or vice versa.

Pool host: respectfreedom.com
Pool port: 3330
Pool user: sfgZuKwSR71cyo8aZb74jeGRhVrxcFk2Mp
Pool pass: sfgZuKwSR71cyo8aZb74jeGRhVrxcFk2Mp
Algorithm: Scrypt

Establishing connection with pool respectfreedom.com:3330... OK
Sending mining.subscribe... OK
Sending mining.authorize... OK
Received mining.notify subscription... OK
Received mining.set_difficulty... OK
Received unknown stratum message.
Received mining.notify work... OK
Received authorization result... OK

Pool verification process is complete. Tested pool is compatible!
##

**Comment by jdghenderson** [comment]
If you are having trouble connecting to a pool either using local or cloud miners please download this Stratum Proxy and configure as follows as a shortcut on windows (demo info using pool.803mine.com for MadCoin):

https://mining.bitcoin.cz/media/download/mining_proxy.exe 

C:\miningproxy\mining_proxy.exe -o pool.803mine.com -p 3349 -sp 3449 -gp 3549

A run down:

-o is the server address of pool so our pool address: pool.803mine.com

-p is the real port from pools getting started page, in this example Madcoin: 3349

-sp is the local PC stratum port to connect your mining equipment to, in this example: 3449 but can be anything as long as it's not in use (try this port first in your miner config)

-gp is the local PC getwork port to connect your mining equipment to, in this example: 3549 but can be anything as long as it's not in use (if the above doesn’t work please try this one in your miner config, always works as a fallback if above fails)

If your running locally, for example miner is on the same network as your computer then point your miner at your computers IP address and use the -sp port configured as your miners port and if that fails the -gp port configured. (make sure you allow the proxy program inboud access in windows firewall from your local network miners)

If you rent a web miner you will need to point it at your router’s IP address, then port forward (3449 and 3549, in this example or ports you configure yourself) to your PC running the proxy (make sure windows firewall allows this program inbound connections, if possible lock down to only accept miners IP address if internet based and not local).

Hope this helps until new stratum implementation is in place or developed.

Thanks!
