### ISSUE TITLE
zeusminer.com - Unable to connect - CG MINER for win V3.0

### ISSUE THREAD

**Issue by agentsmith5443** [bonesoul/CoiniumServ#708]
https://zeusminer.com/user-manual-ver-1-0/

CG MINER for win V3.0 https://mega.co.nz/#!FtBiHRRR!ws1MEg1x9XMHc-M7WyKeUmdWxQxFaTY1mcEIfo0hRsk

The only way to get this version working with CoiniumServ is mining proxy.

Any Advice?

Here is the mining proxy.
https://mining.bitcoin.cz/mining-proxy-howto
##

**Comment by BadWolf-63** [comment]
i have 3 GAW Fury connected via USB-COM port with Bfgminer with no problem, aside the wrong ashrate displayed.

**Comment by computeronix** [comment]
Tested working
