### ISSUE TITLE
Cannot authenticate miner

### ISSUE THREAD

**Issue by Cryptix23** [bonesoul/CoiniumServ#714]
I'm trying to reach my stratum on my server but unable to auth my miner.

I'm running coinium on port 8080 and proxied with Apache to port 80 for the website.

Startum is binded to 0.0.0.0:3339 but when try to connect with mi miners for a test i get "Stratum authentication failed" error message in console.

Please help.

**Comment by Netzarim** [comment]
I am having the same problem, what did you change?
