### ISSUE TITLE
vhub 1.0.0-RC4 @ 2014-12-13 & Ledokol

### ISSUE THREAD

**Issue by omh-WiZaRd** [bonesoul/CoiniumServ#715]
Hello,
I have a problem with verlihub 1.0.0-RC4 @ 2014-12-13 and Ledokol 2.8.4. I am abble to generate a chat room using the command: !chatadd nick desc 1 10 \* however if I join the room and type something nowone will receive any messages, +help dosent work either.
##

**Comment by bonesoul** [comment]
???
