### ISSUE TITLE
High Hashrate/Orphaned Blocks?

### ISSUE THREAD

**Issue by daygle** [bonesoul/CoiniumServ#724]
Hoping someone can help, I have just recently setup CoiniumServ with three pools and at first everything seems ok...

Saying that hashrates for all my pools are overstated? I have no idea why? I followed all getting started instructions.

Additionally to this my pools are finding blocks but marking them as orphaned?

Any pointers to why this is happening? How can I fix this?
##

**Comment by daygle** [comment]
Ok I sorted out the hashrate issue, I'm now just experiencing high hashrates (around double the hashrate of the real hashrate).

Anyone able to provide advise?

**Comment by tomgie** [comment]
Its a current problem at the moment.

**Comment by crusher72** [comment]
No fixes still?

**Comment by tomgie** [comment]
CoiniumServ has been abandoned I think.

**Comment by daygle** [comment]
Yeah I have totally given up on CoiniumServ

**Comment by daygle** [comment]
Closing case because of the lack of maintenance of this source code.
