### ISSUE TITLE
lyra2re , neoscrypt,quark algo support in c# - placing bounty

### ISSUE THREAD

**Issue by frndxyz** [bonesoul/CoiniumServ#728]
##

**Comment by frndxyz** [comment]
can you build it for me?, @raistlinthewiz

**Comment by frndxyz** [comment]
i compiled neoscrypt and lyra2re. but one help need from you.
what is multiplier for neoscrypt, lyra2re, quark ? can you guide me?.  and please cancel bounty, if possible.

**Comment by frndxyz** [comment]
compiled dll my self and call from c#, works great here.. http://hashgoal.com . but still higher hashrate  issue need to fix, but complicated...

**Comment by trickyriky** [comment]
any advise or idiot guide on adding neoscrypt to coiniumserv please guys

**Comment by vkynchev** [comment]
@frndxyz As of your pool is down right now could you post from where you found NeoScrypt & Lyra2re's c# source to compile them?
