### ISSUE TITLE
MySQL Database Structure

### ISSUE THREAD

**Issue by arkestra** [bonesoul/CoiniumServ#729]
I cannot find reference to the MySQL Database structure anywhere, and I'm getting errors such as:

"[Error] [MposStorage] [Bitcoin] An exception occurred while reading pool_worker table; Table 'mpos.pool_worker' doesn't exist"

Is the structure supposed to be built on first load, or was the starting structure's inclusion just overlooked in the git repo?
##

**Comment by raistlinthewiz** [comment]
If you enabled mpos mode, the mpos should be create it's own tables.

**Comment by arkestra** [comment]
The database connection has been set in pools/default.json, and pools/pool.json.  The connection is confirmed when CoiniumServ boots:
11:48:52 [Information] [MySqlProvider] [Bitcoin] Mysql storage initialized: 127.0.0.1:3306, database: mpos.

Config Excerpts

Deafult.js - http://pastebin.com/raw.php?i=xxWy3GZc
Pool.json - http://pastebin.com/raw.php?i=QWHDEKrW

Is there another location that mpos could be configured/enabled?

**Comment by raistlinthewiz** [comment]
You should be following this; https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide
