### ISSUE TITLE
Many Errors Including Cannot Connect To The Remote Server

### ISSUE THREAD

**Issue by geekphazm** [bonesoul/CoiniumServ#733]
Hello,

I am having an issue on a Windows server. 

If you could point me in the direction to look specifically where the issue is that would be great! 
![error](https://cloud.githubusercontent.com/assets/13191539/8529111/eaf538ce-23e5-11e5-9f68-2a025b95e29c.PNG)
##

**Comment by geekphazm** [comment]
Whoops, made a small MySQL error. Now I keep getting the Redis error, and I do have the Redis Client started, and went into npm cmd and did "redis-commander" and it loaded fine.

**Comment by ferni** [comment]
Question, I'm having a similar problem. Did configuring MySQL correctly solved your connection error to the bitcoin node?

**Comment by computeronix** [comment]
this should be resolved with latest version
