### ISSUE TITLE
./CoiniumServ [Error] [n/a] [global] Can not read json file /home/administrator/CoiniumServ/bin/Release/config/markets.json

### ISSUE THREAD

**Issue by dy08aab** [bonesoul/CoiniumServ#735]
when i run the coinium in Ubuntu, it showed the message: [Error] [n/a] [global] Can not read json file /home/administrator/CoiniumServ/bin/Release/config/markets.json
21:08:45 [Error] [MarketsConfig] [global] Error loading website statistics configuration
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform member binding on `null' value
at (wrapper dynamic-method) object.CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object) <0x000e1>
at System.Dynamic.UpdateDelegates.UpdateAndExecute1<object, object> (System.Runtime.CompilerServices.CallSite,object) <0x00534>
at CoiniumServ.Markets.MarketsConfig..ctor (object) <0x002f6>

21:08:45 [Error] [n/a] [global] Can not read json file /home/administrator/CoiniumServ/bin/Release/config/software.json
21:08:45 [Error] [n/a] [global] Json parsing failed for: config/pools/litecoin.json - Extraneous value delimiter
21:08:45 [Information] [ConfigManager] [global] Discovered a total of 0 enabled pool configurations: []
21:08:56 [Error] [WebServer] [global] Need elevated privileges to listen on port 80, try running as root - Access denied
21:16:04 [Error] [CryptsyClient] [global] `bool' does not contain a definition for`markets'
21:20:05 [Error] [CryptsyClient] [global] `bool' does not contain a definition for`markets'
21:28:10 [Error] [ExchangeApi] [global] The operation has timed out.
21:28:10 [Error] [BittrexClient] [global] Cannot perform member binding on `null' value
21:44:11 [Error] [ExchangeApi] [global] The operation has timed out.
21:44:11 [Error] [BittrexClient] [global] Cannot perform member binding on`null' value
21:50:00 [Error] [ExchangeApi] [global] The operation has timed out.
21:50:00 [Error] [BittrexClient] [global] Cannot perform member binding on `null' value
21:57:08 [Error] [ExchangeApi] [global] The operation has timed out.
21:57:08 [Error] [BittrexClient] [global] Cannot perform member binding on`null' value
pls help. really headache now.
##

**Comment by computeronix** [comment]
there is no markets.json config file in the location mentioned (possibly file not exist) /home/administrator/CoiniumServ/bin/Release/config/

**Comment by bonesoul** [comment]
You can use this.

https://github.com/bonesoul/CoiniumServ/blob/develop/src/CoiniumServ/config/markets-example.json

**Comment by laugh26** [comment]
how about this 18:30:43 [Error] [WebServer] [global] Need elevated privileges to listen on port 80, try running as root - Address already in use

**Comment by bonesoul** [comment]
Make sure no other process uses port 80, or change the port 80 on config file.

**Comment by laugh26** [comment]
So should i change it to just any port of my making?

**Comment by bonesoul** [comment]
Anything higher then 1024 should be good to go

**Comment by laugh26** [comment]
ok, thanks mentor

**Comment by bonesoul** [comment]
you are welcome.
