### ISSUE TITLE
Advanced config examples missing from repo

### ISSUE THREAD

**Issue by nightrid3r** [bonesoul/CoiniumServ#737]
In the wiki there are references to advanced config examples but those are not included in the repo.
##

**Comment by durilup** [comment]
I'd like to have one of these as well

**Comment by Thomasmcdaniel9** [comment]
Hey are there any good install directions on getting coinuimserv installed

**Comment by durilup** [comment]
Not really. I mean, you basically just install http://www.mono-project.com/download/ and then compile the source to get it running

change some settings in /config fixes most things. But I'd love for there to be a much better documentation

**Comment by Thomasmcdaniel9** [comment]
Yea that would be nice if someone made a step by step instruction manual so
us new pool builders would have a reference to go on.but hey if you run
across any good video tutorials shoot me one I've never made a pool just
want to learn
