### ISSUE TITLE
[Error] [CryptsyClient] [global] Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by sixxkilur** [bonesoul/CoiniumServ#738]
Constant error on Windows 7 Ultimate 64bit and windows 10 Pro 64bit. Tried two different versions; v0.2.4.28875 and v0.2.4.31548
##

**Comment by crusher72** [comment]
Bonesoul says to disable Cryptsy, but I am waiting for a reply as to how.

*BUMP*

**Comment by RiteshPanda** [comment]
BUMP
I want the solution too

**Comment by BaalMcKloud** [comment]
check `CoiniumServ\src\CoiniumServ\Markets\MarketManager.cs` on line 56 !
remove `ICryptsyClient cryptsyClient` and build again.

i tested it and it worked without any errors on the console

**Comment by computeronix** [comment]
Resolved https://github.com/bonesoul/CoiniumServ/pull/770
