### ISSUE TITLE
An exception occured while getting account; Unknown column 'a.coin_address' in 'field list'

### ISSUE THREAD

**Issue by djspacedevil** [bonesoul/CoiniumServ#741]
An exception occured while getting account; Unknown column 'a.coin_address' in 'field list'

In the table accounts no field with name coin_address...

so there is a new table: coin_addresses

Helps here only to change 
MposStorage.Accounts.cs
`return connection.Query<Account>(
                        @"SELECT a.id, w.username, a.coin_address as address FROM pool_worker as w
                            INNER JOIN accounts as a ON a.id=w.account_id
                            WHERE w.username = @username",
                        new {username}).Single();`

to the new Table??
##

**Comment by Chooka** [comment]
return connection.Query<Account>( @"SELECT a.id, w.username, a.coin_address as address FROM pool_worker as w INNER JOIN coin_addresses as a ON a.id=w.account_id WHERE w.username = @username", new {username}).Single();
