### ISSUE TITLE
WARNING! VIRUS FOUND!?

### ISSUE THREAD

**Issue by djspacedevil** [bonesoul/CoiniumServ#742]
/CoiniumServ/build/.nuget/NuGet.exe: Win.Adware.Agent-59074 FOUND
##

**Comment by raistlinthewiz** [comment]
You compiled it yourself?

**Comment by djspacedevil** [comment]
yes

**Comment by raistlinthewiz** [comment]
Check your system then.

**Comment by computeronix** [comment]
this has been checked and works fine -- might have been a false positive
