### ISSUE TITLE
[MySqlProvider] [Bitcoin] Mysql storage initialized: 127.0.0.1:3306, database: null. 

### ISSUE THREAD

**Issue by ARogovsky** [bonesoul/CoiniumServ#744]
Hi!
I have this bitcoin config:

```
{
    "enabled": true,
    "coin": "bitcoin.json",
    "daemon": {
        "port": 10456,
        "username": "***",
        "password": "***"
        },
    "wallet": {
        "address": "***"
        },
        "rewards":  [
                {"***": 1} 
                 ],
    "stratum": {
        "port": 3333
    },
    "storage": {
        "mpos": {
            "enabled": true,
            "mysql": {
                "host": "127.0.0.1",
                "port": 3306,
                "user": "poolserver",
                "password": "***",
                "database": "bitcoin"
            }
        }
    }
}

```

When I was started CoiniumServ - it throw me this error:
`[MySqlProvider] [Bitcoin] Mysql storage initialized: 127.0.0.1:3306, database: null.`
Can you advice?
##

**Comment by cirscudei** [comment]
You need to create the "bitcoin" database within MySQL, create the user with permissions on that database, and import the base structure.

**Comment by ARogovsky** [comment]
Of course, I was create db, assign user with permissions and import structure.
This bug looks as CoiniumServ missread db name from config.

**Comment by cirscudei** [comment]
I see.  The error looks like it's being thrown when the storage is initialized, which would be before the bitcoin config is loaded.

Double-check all config files pool.json / config.json / markets.json ?

**Comment by ARogovsky** [comment]
There is all errors, all other is good:
`14:00:31 [Error] [ExchangeApi] [global] Unexpected character encountered while parsing value: <. Path '', line 0, position 0. 14:00:31 [Information] [MySqlProvider] [Bitcoin] Mysql storage initialized: 127.0.0.1:3306, database: null. 14:00:31 [Error] [CryptsyClient] [global] Cannot perform member binding on `null' value 14:00:32 [Information] [BanManager] [Bitcoin] No expired bans found to be cleared [remaining bans: 0]. I show errors is present
`

**Comment by ARogovsky** [comment]
Any updates?

**Comment by computeronix** [comment]
this appears to be fixed and working
