### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by crusher72** [bonesoul/CoiniumServ#759]
I get build errors now if I build CS under Windows. I did not before. Here they are:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'RedisClient' could not be found (are you missing a using directive or an assembly reference?)	CoiniumServ	C:\Users\robin\Downloads\CoiniumServ-develop\CoiniumServ-develop\src\CoiniumServ\Persistance\Providers\Redis\RedisProvider.cs	35	Active
Error	CS0246	The type or namespace name 'CSRedis' could not be found (are you missing a using directive or an assembly reference?)	CoiniumServ	C:\Users\robin\Downloads\CoiniumServ-develop\CoiniumServ-develop\src\CoiniumServ\Persistance\Providers\Redis\IRedisProvider.cs	24	Active
Error	CS0246	The type or namespace name 'RedisClient' could not be found (are you missing a using directive or an assembly reference?)	CoiniumServ	C:\Users\robin\Downloads\CoiniumServ-develop\CoiniumServ-develop\src\CoiniumServ\Persistance\Providers\Redis\IRedisProvider.cs	32	Active
Error	CS0246	The type or namespace name 'CSRedis' could not be found (are you missing a using directive or an assembly reference?)	CoiniumServ	C:\Users\robin\Downloads\CoiniumServ-develop\CoiniumServ-develop\src\CoiniumServ\Persistance\Providers\Redis\RedisProvider.cs	26	Active

Hopefully this can be resolved!

Thank you!

**Comment by computeronix** [comment]
this is resolved and be sure to do the following

git clone https://github.com/CoiniumServ/CoiniumServ.git
cd CoiniumServ
git submodule init
git submodule update


the gitsubmodule init and gitsubmodule update were missed so you didnt have csredis to build off of

**Comment by bonesoul** [comment]
closing this then.
