### ISSUE TITLE
Is it curecoin supported by coinium?

### ISSUE THREAD

**Issue by AndreyNag** [bonesoul/CoiniumServ#767]
Is it curecoin supported by coinium?

**Comment by bonesoul** [comment]
Not sure, depens on the algorithm.

**Comment by jdghenderson** [comment]
Yes Curecoin works on CoiniumServ I am using it.

**Comment by bonesoul** [comment]
Thanks for the info.

**Comment by jdghenderson** [comment]
No worries at all @bonesoul here is the coin config I use (the blockchain links need tweaking though to load properly):

{
    "name": "Curecoin",
    "symbol": "CURE",
    "algorithm": "sha256",
    "site": "https://curecoin.net/",
    "blockExplorer": {
        "block": "https://chainz.cryptoid.info/cure/block/",
        "tx": "https://chainz.cryptoid.info/cure/transaction/",
        "address": "hhttps://chainz.cryptoid.info/cure/address/"
    },
    "options": {
		"isProofOfStakeHybrid": true,
		"blockTemplateModeRequired": true,
		"useDefaultAccount": true,
		"txMessageSupported": true		
    }
}

Thanks!
