### ISSUE TITLE
use ctstone/csredis instead?

### ISSUE THREAD

**Issue by bonesoul** [bonesoul/CoiniumServ#775]
As we have already merged latest changes (https://github.com/CoiniumServ/csredis/pull/2) i guess we can safely update our .gitmodules reference and use it. We can even target a specific commit from csredis repo that's known to be working.

I've checked our changes here;
https://github.com/ctstone/csredis/compare/master...CoiniumServ:master

And it seems only that we have re-targeted it to .net 4.5.
Given that we can reference .net 4.0 assemblies from 4.5, it seems fine. (http://stackoverflow.com/a/25499499/170181)

What do you think @computeronix?

**Comment by computeronix** [comment]
Back in 2014 you made some globalization commits.  I don't think those were put in the official branch. Are you good with disregarding those changes?

**Comment by bonesoul** [comment]
It seems @ctsstone already got my commits in; https://github.com/ctstone/csredis/commits?author=bonesoul

And from the current diff: it seems we basically have no oustanding changes.

We may give this a try.

**Comment by bonesoul** [comment]
It seems csredis now has a nuget package now; we can even use this package instead of git submodule;

https://www.nuget.org/packages/csredis

**Comment by computeronix** [comment]
Ok lets do that!!  Feel free to make those two changes as I am not as familiar with removing the sub module and replacing it with a nuget pkg

**Comment by computeronix** [comment]
sure can, I will be at the computer later this evening and can test

**Comment by bonesoul** [comment]
Okay we'll be nice if you can test this branch: https://github.com/bonesoul/CoiniumServ/tree/feature/csredis-package

**Comment by computeronix** [comment]
looking good!!  much easier to setup and manage too

litecoin seems to be hashing away with the test

**Comment by bonesoul** [comment]
nice i'll merge this once the tests are done then.

**Comment by bonesoul** [comment]
closed with #776.
