### ISSUE TITLE
Why CoiniumServ does not needed a Shares table on the DB?

### ISSUE THREAD

**Issue by jeong760** [bonesoul/CoiniumServ#792]
Dears,

In order to StramBuffered error, CoiniumServ needs to write down shares from a miner in MySql DB.
if not, it will continuously use a Redis Storages may occur a Buffer memory errors like I have. 

Could you explain to me why Shares table does not exist on MySql DB in order to store a share data from miners? I saw the code on IStorageLayers.cs for Share Storage but after I could not find any table create command for Shares DB anywhere

Following example table, I bring it from MPOS for shares. it uses the same method but it records an every share from miner into MySql DB. I think you will consideration to use a this or similar method to save a share from miner

CREATE TABLE IF NOT EXISTS `shares` (
  `id` bigint(30) NOT NULL AUTO_INCREMENT,
  `rem_host` varchar(255) NOT NULL,
  `username` varchar(120) NOT NULL,
  `our_result` enum('Y','N') NOT NULL,
  `upstream_result` enum('Y','N') DEFAULT NULL,
  `reason` varchar(50) DEFAULT NULL,
  `solution` varchar(257) NOT NULL,
  `difficulty` float NOT NULL DEFAULT '0',
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `time` (`time`),
  KEY `upstream_result` (`upstream_result`),
  KEY `our_result` (`our_result`),
  KEY `username` (`username`),
  KEY `shares_username` (`username`(10))
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

**Comment by bonesoul** [comment]
Redis is solely used for shares.

**Comment by jeong760** [comment]
Dears,

Yes, I know that Redis for Shares. but we cannot store a Shares until fund a new block. and also this will cause a StreamBuffer issues due to limited of memory space matter. 

Could you guide me where I can modify to save a share into MySql DB?

**Comment by bonesoul** [comment]
you need to implement a storage layer then. https://github.com/bonesoul/CoiniumServ/tree/develop/src/CoiniumServ/Persistance/Layers

MPOS is a sample one.
