### ISSUE TITLE
Digibyte sha256d

### ISSUE THREAD

**Issue by Controlhosting** [bonesoul/CoiniumServ#798]
it wont show network hashrate i have exhausted all things daemon. the only other thing i can think is coiniumserv

**Comment by jeong760** [comment]
Dears,

Because of the csredis plugin and some code issues on CoiniumServ you cannot get a hash rate of your pool properly. So I think you will move to another software like unomp or eloipool

**Comment by bonesoul** [comment]
Need more details on this.

**Comment by jdghenderson** [comment]
I think I know the issue here I am just not sure how to code in the changes, essentially the Digibyte and Auroracoin wallets use "getnetworkhashps" instead of the standard "networkhashps" all other wallet's use. If this can be accomodated then it should display correctly. Thanks

**Comment by bonesoul** [comment]
You need to change the call for getnetworkhashps in the code then.

**Comment by bonesoul** [comment]
Basically those shitcoin authors are changing the standart api call names and it's nearly impossible to track all of them.

**Comment by jdghenderson** [comment]
I agree I have no idea why they would change it from the standard. Is there a simple way I could add this in as an extra procedure if the normal networkhashps doesnt respond or gets a bad response? I am trying to keep the original code to cater for normal wallets as well as these shitcoins haha. Thanks

**Comment by bonesoul** [comment]
You can basically add a config option to coin and check if the bool is enabled and then fire networkhashps/getnetworkhashps based on it.

**Comment by jdghenderson** [comment]
Thanks @bonesoul I will give that a go. Cheers!
