### ISSUE TITLE
something weird when i run it on linux

### ISSUE THREAD

**Issue by zhiyan114** [bonesoul/CoiniumServ#799]
how do i fix this:

./CoiniumServ.exe:

 1: ./CoiniumServ.exe: MZ▒▒▒▒@▒▒▒: not found
./CoiniumServ.exe: 1: ./CoiniumServ.exe: ▒D,O@: not found
./CoiniumServ.exe: 1: ./CoiniumServ.exe: .rsrc: not found
./CoiniumServ.exe: 2: ./CoiniumServ.exe: Ģ: not found
./CoiniumServ.exe: 73: ./CoiniumServ.exe: Syntax error: ";" unexpected (expectin                                                                                        g ")")

**Comment by bonesoul** [comment]
you need mono.

**Comment by zhiyan114** [comment]
thx, yes i did install all the required stuff (include mono-complete)

**Comment by bonesoul** [comment]
try running with mono ./CoiniumServ.exe

**Comment by zhiyan114** [comment]
THX, it worked (i use sudo on raspberry pi and works and this one not) now use mono works, THANKS

**Comment by bonesoul** [comment]
you are welcome.
