### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by EmizGaming** [bonesoul/CoiniumServ#804]
I have been getting the same message over and over again, tried changing the configs and everything I can come up with. Anyone got the same problem or a solution? 
![09983a3398174045b82a02e78e93766c](https://cloud.githubusercontent.com/assets/16196784/26644863/d7c57318-463e-11e7-9694-09c7263e2ccc.png)

**Comment by bonesoul** [comment]
check your daemon config.

**Comment by jdghenderson** [comment]
Yes looks like your wallet address you have specified in your pool config doesnt match up with the wallet it is connecting to. Once the master receiving address of your wallet is updated in your config restart coiniumserv and you should be golden. Thanks
