### ISSUE TITLE
The CoiniumServ networking randomly dies after a while 3-5 hours and requires a restart.

### ISSUE THREAD

**Issue by 57-Wolve** [bonesoul/CoiniumServ#805]
Here's an issue I've been trying to figure out I keep seeing JobManger and NetworkManager errors like these.

16:50:32 [Error] [JobManager] [Dogecoin] New job creation failed: An unknown exception occured while making json request.

16:58:19 [Error] [NetworkInfo] [Dogecoin] Can not probe submitblock() support: An unknown exception occured while making json request.
16:58:19 [Error] [NetworkInfo] [Dogecoin] Can not read getblocktemplate(): An unknown exception occured while making json request.

I test the commands using dogecoin-cli and it returns availed output.

The network randomly dies after awhile and requires a restart.
Seems to have something to do with the networking between the RPC and ConiumServ as it will spam errors about networking, like what's seen above. Makes me think I don't have the RPC server set-up right.

**Comment by Broatcast** [comment]
Same here with other CoinDeamon, running fine for a few hours then die with same errors. The CoinDeamon is still running and reachable. Repsond normal to commands from cli. Nothing in the log.

Next problem is that the user id's are not persistant and lost the shares info all 3-5 mins.

**Comment by bonesoul** [comment]
It seems CS is loosing connectivity with coin daemon, a full log may help.
