### ISSUE TITLE
WEB Interface access

### ISSUE THREAD

**Issue by kevinmitnik** [bonesoul/CoiniumServ#806]
},
    "website": {
        "enabled": true,
        "bind": "0.0.0.0",
        "port": 80,
        "template": "default",
        "feed": "",
        "backend": {
            "metrics": {
                "enabled": true
            }
        }
    },

http://my_site_name.ru/

Erorr:  Bad Request (Invalid host)

**Comment by kevinmitnik** [comment]
If i set:  
` "bind": "my_site_name.ru" `
or 
` "bind": "17.17.17.17" `

I got error:

`12:43:09 [Error] [WebServer] [global] Need elevated privileges to listen on port 80, try running as root - The requested address is not valid in this context`

But I already run under root 
`#mono ./CoiniumServ.exe`

SELinux disabled

**Comment by bonesoul** [comment]
send me your 
`whoami` output please

**Comment by kevinmitnik** [comment]
# whoami
root

**Comment by bonesoul** [comment]
could be related to interface you try to bind to?

**Comment by kevinmitnik** [comment]
Solved.

**Comment by wassereimer86** [comment]
I hate it. Just writing "Solved" but not telling the rest of the world what the solution was.

**Comment by bonesoul** [comment]
probably he had a problem with his interface config.

**Comment by ncrmro** [comment]
I'm also getting this same error behind docker containers at the moment, any idea why?

**Comment by ncrmro** [comment]
Leaving config as is from example got me working no need to bind website to 0.0.0.0

```
"website": {
    "enabled": true,
    "bind": "",
    "port": 80,
    "template": "default",
    "feed": "",
    "backend": {
      "metrics": {
        "enabled": false
      }
    }
  },
```
