### ISSUE TITLE
Unable to run  ./CoiniumServ missing after build ubuntu 17.04 or lite not working

### ISSUE THREAD

**Issue by mario1987** [bonesoul/CoiniumServ#808]
can't run CoiniumServ after build missing file or  file not working

~/CoiniumServ/src/Tests/bin/Release$ ./CoiniumServ
-bash: ./CoiniumServ: No such file or directory

mario@mario-pool:~/CoiniumServ/bin/Debug$ sudo ./CoiniumServ.exe
sudo: ./CoiniumServ.exe: command not found
mario@mario-pool:~/CoiniumServ/bin/Debug$ ./CoiniumServ.exe
-bash: ./CoiniumServ.exe: Permission denied
mario@mario-pool:~/CoiniumServ/bin/Debug$

Build log below

mario@mario-pool:~/CoiniumServ/build/release$ ./build.sh
Mozilla Roots Importer - version 5.0.1.1
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

WARNING: mozroots is deprecated, please move to cert-sync instead.

Downloading from 'https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...
Importing certificates into user store...
1 new root certificates were added to your trust store.
Import process completed.

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 5.0.1.1
Copyright (C) 2005-2013 Various Mono authors

Build started 6/5/2017 3:52:28 PM.
__________________________________________________
Project "/home/mario/CoiniumServ/build/CoiniumServ.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Release|Mixed Platforms".
        Target Build:
                Project "/home/mario/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj" (default target(s)):
                        Target RestorePackages:
                                Executing: mono --runtime=v4.0.30319 /home/mario/CoiniumServ/build/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/mario/CoiniumServ/build/"
                                Restoring NuGet packages...
                                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                                Feeds used:
                                  /home/mario/.nuget/packages/
                                  https://api.nuget.org/v3/index.json
                                All packages listed in /home/mario/CoiniumServ/src/CoiniumServ/packages.config are already installed.
                        Target PrepareForBuild:
                                Configuration: Release Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target _GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                        Target _CopyDeployFilesToOutputDirectoryPreserveNewest:
                        Skipping target "_CopyDeployFilesToOutputDirectoryPreserveNewest" because its outputs are up-to-date.
                        Target _CopyAppConfigFile:
                        Skipping target "_CopyAppConfigFile" because its outputs are up-to-date.
                        Target AfterBuild:
                                Copying file from '/home/mario/CoiniumServ/build/packages/Nancy.Viewengines.Razor.0.23.2/BuildProviders/Nancy.ViewEngines.Razor.BuildProviders.dll' to '/home/mario/CoiniumServ/bin/Release/Nancy.ViewEngines.Razor.BuildProviders.dll'
                                Copying file from '/home/mario/CoiniumServ/build/packages/Nancy.Viewengines.Razor.0.23.2/lib/net40/Nancy.ViewEngines.Razor.dll' to '/home/mario/CoiniumServ/bin/Release/Nancy.ViewEngines.Razor.dll'
                Done building project "/home/mario/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".
                Project "/home/mario/CoiniumServ/src/Tests/CoiniumServ.Tests.csproj" (default target(s)):
                        Target RestorePackages:
                                Executing: mono --runtime=v4.0.30319 /home/mario/CoiniumServ/build/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/mario/CoiniumServ/build/"
                                Restoring NuGet packages...
                                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                                Feeds used:
                                  /home/mario/.nuget/packages/
                                  https://api.nuget.org/v3/index.json
                                All packages listed in /home/mario/CoiniumServ/src/Tests/packages.config are already installed.
                        Target PrepareForBuild:
                                Configuration: Release Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target _GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "_GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                        Target _CopyDeployFilesToOutputDirectoryPreserveNewest:
                        Skipping target "_CopyDeployFilesToOutputDirectoryPreserveNewest" because its outputs are up-to-date.
                        Target _CopyAppConfigFile:
                        Skipping target "_CopyAppConfigFile" because its outputs are up-to-date.
                Done building project "/home/mario/CoiniumServ/src/Tests/CoiniumServ.Tests.csproj".
Done building project "/home/mario/CoiniumServ/build/CoiniumServ.sln".

Build succeeded.
         0 Warning(s)
         0 Error(s)

Time Elapsed 00:00:03.9060670
xUnit.net console test runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2013 Outercurve Foundation.

xunit.dll:     Version 1.9.2.1705
Test assembly: /home/mario/CoiniumServ/src/Tests/bin/Release/CoiniumServ.Tests.dll

48 total, 0 failed, 0 skipped, took 0.987 seconds

**Comment by bonesoul** [comment]
try `mono ./CoiniumServ`

**Comment by mario1987** [comment]
it worked tnx  i needed to do sudo mono ./CoiniumServ.exe

**Comment by mario1987** [comment]
I have got it to work, but now i am getting these errors 

19:33:14 [Error] [RedisProvider] [Litecoin] Redis storage initialization failed: 212.168.1.207:6379 - This method is not implemented by this class.

19:33:14 [Error] [MigrationManager] [Litecoin] An exception occured while running migration manager; No database selected

19:33:15 [Error] [JobManager] [Litecoin] New job creation failed: Support for 'segwit' rule requires explicit client support

19:33:15 [Error] [NetworkInfo] [Litecoin] Can not read getblocktemplate(): Support for 'segwit' rule requires explicit client support

any idea on how to solve these ?
