### ISSUE TITLE
How to use admin panel or metrics?

### ISSUE THREAD

**Issue by foxer666** [bonesoul/CoiniumServ#811]
"website": {
        "enabled": true,
        "bind": "",
        "port": 8080,
        "template": "default",
        "feed": "",
        "backend": {
            "metrics": {
                "enabled": true				
            }
        }
    },

/metrics/

The requested resource could not be found.

**Comment by vkynchev** [comment]
@foxer666 Coiniumserv does not have admin panel... The config is about the c# backend...

**Comment by bonesoul** [comment]
That backend is purelly
