### ISSUE TITLE
PoolManager error recaching statistics; the method or operation is not implemented 

### ISSUE THREAD

**Issue by pfeiflelukas** [bonesoul/CoiniumServ#815]
I have setup CoiniumServ without any storage, MPOS and hybrid, as i am just testing for myself. From what i can determine this is not a serious issue, and only effects the statistics of the front end. I can connect a miner which authenticates and then shows shares are being accepted. The front end updates and shows a worker is connected and even shows the number of shares being accepted. However, the pool hashrate, last block and profitability do not update. I have left a miner connect for 24hrs to see if a block needs to be found first in order for the statistics to be valid, but no luck yet.

I have tried to delete cryptsy but it is no longer located in MarketManager. Am i getting this error because i have not setup MPOS or a storage system? 

Any help would be great

10:37:54 [Information] [ConfigManager] [global] CoiniumServ Aurora 0.2.5.35039 warming-up..
10:37:54 [Information] [PlatformManager] [global] Running over .Net, framework: 4.5 (v4.0.30319.42000).
10:37:55 [Error] [StorageConfig] [global] Storage will be not working as no valid storage configuration was found!
10:37:55 [Information] [ConfigManager] [global] Discovered a total of 1 enabled pool configurations: [Dogecoin]
10:37:55 [Debug] [Pool] [Dogecoin] Generated cryptographically random instance Id: 2482820664
10:37:55 [Debug] [n/a] [global] Metrics: GlobalContext Name set to CoiniumServ
10:37:55 [Information] [BanManager] [Dogecoin] No expired bans found to be cleared [remaining bans: 0].
10:37:55 [Information] [JobManager] [Dogecoin] Broadcasted new job 0x1 to 0 subscribers as no new blocks found for last 55 seconds
10:37:55 [Information] [NetworkInfo] [Dogecoin] symbol: DOGE algorithm: scrypt version: 1100000 protocol: 70004 wallet: 60000 network difficulty: 101404.86754498 block difficulty: 6645669399.43 network hashrate: 6.42 TH/s network: mainnet peers: 16 blocks: 1766444 errors: none
10:37:55 [Information] [StratumServer] [Dogecoin] Stratum server listening on 0.0.0.0:3337
10:37:55 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.
10:37:55 [Debug] [StatisticsManager] [global] Recached statistics - took 0.014 seconds
10:37:55 [Information] [WebServer] [global] Web-server listening on: http://localhost/
10:37:56 [Debug] [MarketManager] [global] Recached market data - took 1.229 seconds
10:37:57 [Debug] [StratumServer] [Dogecoin] Stratum client connected: "192.168.0.230:38610"
10:37:57 [Debug] [MinerManager] [Dogecoin] Authenticated miner: DJXBq7pXLWw91JJGbaCKz3wZ1vMkfHW4TA [192.168.0.230:38610]
10:38:01 [Debug] [ShareManager] [Dogecoin] Share accepted at 45.43/16 by miner DJXBq7pXLWw91JJGbaCKz3wZ1vMkfHW4TA
10:38:01 [Debug] [ShareManager] [Dogecoin] Share accepted at 54.46/16 by miner DJXBq7pXLWw91JJGbaCKz3wZ1vMkfHW4TA
10:38:01 [Debug] [ShareManager] [Dogecoin] Share accepted at 67.88/16 by miner DJXBq7pXLWw91JJGba

**Comment by BaalMcKloud** [comment]
You need a db for stats if i remember right?!

**Comment by pfeiflelukas** [comment]
Thanks for the reply.
Just configured the hybrid storage and the pool hashrate is now found. Still now stats on the last block found or profitability. Do i need to just find a block and then mine it for these to be displayed?

**Comment by mario1987** [comment]
Where must the db be found  on redis or msql ? because i have configured the redis and the msql and it still not showing blocks found while i am actually are finding blocks.

**Comment by pfeiflelukas** [comment]
In the same position as you @mario1987. What are you mining to find blocks? A relatively new scrypt coin with low difficulty?

**Comment by mario1987** [comment]
I am mining x11 ReddBytecoin  and found over 2000 coins

**Comment by pfeiflelukas** [comment]
Doesn't give me a lot of hope that my pool will start to update the statistics. Does it have to me a MPOS db?
