### ISSUE TITLE
Found blocks are not displayed in front end

### ISSUE THREAD

**Issue by pfeiflelukas** [bonesoul/CoiniumServ#820]
Hi all,

I have successfully implemented CoiniumServ and no longer get any major errors. However, the front end does not update the blocks found by the miners as well as the profitability of each coin available. Anyone else having this problem and have a solution?

Thanks

**Comment by crusher72** [comment]
It's in the database files, this has been covered before, look into older issues for the same thing. Close this thread.

**Comment by pfeiflelukas** [comment]
Can you please link the issue that the solution is contained in? I have checked twice but found nothing. I could be blind???

Thanks
