### ISSUE TITLE
Is there a guide how I add a new algorithm ?

### ISSUE THREAD

**Issue by RobOrville** [bonesoul/CoiniumServ#824]
Hello guys, 
I have a question today, **is there a guide how I add a new algorithm (for example: Ethereum or Monero) ?**
It would be nice if you can help me,Thanks a lot and have a nice day!

Best regards, 
Robert

**Comment by bonesoul** [comment]
no guide but some sample implementations; https://github.com/bonesoul/CoiniumServ/tree/develop/src/CoiniumServ/Algorithms/Implementations

**Comment by 0xdamm** [comment]
I do not understand why you did not implement it on **master branch** github...

Please consider implementing **ethash** and **equihash** algorithm..

**Comment by bonesoul** [comment]
if someone is willing to implement it, i'll be more then happy to merge it.
