### ISSUE TITLE
No Unix file

### ISSUE THREAD

**Issue by PEVN** [bonesoul/CoiniumServ#825]
So I followed all the steps BUT,
there doesn't exist any file that Ubuntu can run...at least not in bin/Release...
What do I do? There is a .exe but Unix doesn't run it?
Thanks in advance

**Comment by bonesoul** [comment]
You can use mono to run .net executables.

**Comment by BaalMcKloud** [comment]
On Linux there is mono to run Windows Programms. But i dont know if it works or not..

**Comment by PEVN** [comment]
All right but the ./ command doesn't work???

**Comment by PEVN** [comment]
No worries a basic google did the trick
