### ISSUE TITLE
advanced-example.json

### ISSUE THREAD

**Issue by saydulk** [bonesoul/CoiniumServ#827]
This file is broken https://github.com/bonesoul/CoiniumServ/blob/develop/src/CoiniumServ/config/pools/advanced-example.json

**Comment by vagabondan** [comment]
Any chance you provide some details?

**Comment by bonesoul** [comment]
use this instead; https://github.com/bonesoul/CoiniumServ/blob/develop/src/CoiniumServ/config/pools/default-example.json

**Comment by saydulk** [comment]
thanks :) this is what i was looking for!
