### ISSUE TITLE
Cannot write to a bufferedStream error (hybrid / redis)

### ISSUE THREAD

**Issue by pfeiflelukas** [bonesoul/CoiniumServ#831]
Full error: Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.

Can some please explain the cause of this error and how to fix it. I have searched for an answer but each solution i try only temporarily fixes it. Any help is appreciated. 

Thanks

**Comment by pfeiflelukas** [comment]
An update of what is going on: block information on the webpage still saying 0 while last block and last payment are the same. Anyone else had this issue?

**Comment by vagabondan** [comment]
Here
https://github.com/bonesoul/CoiniumServ/issues/826#issuecomment-316766457
