### ISSUE TITLE
Configuration needed for LTC segwit?

### ISSUE THREAD

**Issue by ImrieA** [bonesoul/CoiniumServ#833]
Hello,

I've LTC running with CoiniumServ except I get the constant error of:

`[Error] [NetworkInfo] [Litecoin] Can not read getblocktemplate<>: Support for 'segwit' rule requires explicit client support`

After reading around it appears getblocktemplate from the daemon needs to be getblocktemplate '{"rules":["segwit"]}'

Adding `data.Add("rules", new[] { "segwit" });` to DaemonClient does not seem to solve the issue.

Any tips? Thanks

**Comment by BaalMcKloud** [comment]
Mined a valid block with that change?

**Comment by ImrieA** [comment]
No, not yet. Still in configuration phase

**Comment by BaalMcKloud** [comment]
Please let us know when you mined a valid block with that change.
