### ISSUE TITLE
Unable to locate view 'error'

### ISSUE THREAD

**Issue by xervantex** [bonesoul/CoiniumServ#843]
Hi I have compile from source I have change all the configuration files with the examples you offer and the server seems to be runing well 

07:33:28 [Information] [ConfigManager] [global] CoiniumServ Aurora 0.2.5.12894 warming-up..
07:33:28 [Information] [PlatformManager] [global] Running over Mono 4.6.2 (Debian 4.6.2.7+dfsg-1), framework: 4.5 (v4.0.30319.42000).
07:33:28 [Information] [ConfigManager] [global] Discovered a total of 0 enabled pool configurations: []
07:33:29 [Information] [WebServer] [global] Web-server listening on: http://localhost/

But when I go to the Web Browser I get this error

Could not locate your error view! Details: Unable to locate view 'error'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views//error-es-VE,views//error,/error-es-VE,/error,views/error-es-VE,views/error,error-es-VE,error
Root path: /var/www/html/CoiniumServ/src/Tests/bin/Release/web/default
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'

I have not configure any coin yet

**Comment by vkynchev** [comment]
@xervantex Check to see if the file exists... Linux filesystem is sase sensitive!

**Comment by bonesoul** [comment]
This is caused by Nancy and it's pain in the ass sometime to work with. Need more details (like your config and so).

**Comment by gecox22** [comment]
It has something to do with the Nancy View Engine I posted a solution on how I fixed it over on vagabondan fork. I just copied all of my nancy files and pasted them into his built project. Worked like a charm. I  know it is not the right way but it work. I also posted a link to my files over there as well. I wonder if uninstalling nancy view engine nuget package and reinstalling it would help?
