### ISSUE TITLE
Can CoiniumServ use for Ethereum?

### ISSUE THREAD

**Issue by Namteo** [bonesoul/CoiniumServ#845]
How can i use coiniumServ for ETH?

**Comment by BaalMcKloud** [comment]
You can't use coiniumserv for ETH mining.

**Comment by bonesoul** [comment]
We don't have the code yet in to support ETH mining.

**Comment by MrBeingMan** [comment]
What code are you missing from ETH? Sorry to ask

**Comment by bonesoul** [comment]
Eth's blockchain infrastructure is completely different.

**Comment by MrBeingMan** [comment]
Thank you for answers, sorry I'm new to the development of cryptocurrencies what makes Ethereum different for the other blockchain that makes it harder to implement?
