### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Leadspie** [bonesoul/CoiniumServ#847]
Is this project dead? Are any additional algorithms HP going to be added.?
How do I edit front end, it's not reflecting my changes.

**Comment by xslugx** [comment]
not dead , the team is working on hypeengine. however this is open source so it will get new features when someone does a Pull Request and the features are implimented

**Comment by Obli-One** [comment]
hello, can you tell me if you added the cryptonote algo's to this, I can see an enhancement label but it was from a few years ago.

**Comment by bonesoul** [comment]
Basically I'm not implementing new features on this repo. Though as said, it's welcome for new PR's.

**Comment by Obli-One** [comment]
What if I funded the feature?

**Comment by xslugx** [comment]
@Obli-One you would find a dev to write it then issue a Pull Request, then bonesoul will merge the request to make it live

**Comment by bonesoul** [comment]
Again, the repo is mostly in maintenance stage.
