### ISSUE TITLE
neoscrypt.cs

### ISSUE THREAD

**Issue by Igor-san** [bonesoul/CoiniumServ#854]
`tried to convert it in c# using converter but looks ugly.. here is link.. https://dl.dropboxusercontent.com/u/88514409/neoscrypt.cs`

Hello. I find that you implemented support for neoscript, but the file is not available. Can re-download it, or even better include it in the CoiniumServ?

**Comment by bonesoul** [comment]
It seems the link is not working.  You can find reference implementations here; https://github.com/bonesoul/CoiniumServ/tree/develop/src/CoiniumServ/Algorithms/Implementations

**Comment by Netzarim** [comment]
https://github.com/ghostlander/NeoScrypt

This appears to be the github archive.
