### ISSUE TITLE
The pool can not work properly, the wallet has been normal connection, the port is through

### ISSUE THREAD

**Issue by zhq1** [bonesoul/CoiniumServ#855]
The pool can not work properly, the wallet has been normal connection, the port is through

21:30:54 [Error] [ExchangeApi] [global] Unexpected character encountered while p
arsing value: <. Path '', line 0, position 0.
21:30:54 [Error] [PoloniexClient] [global] Object reference not set to an instan
ce of an object.

**Comment by zhq1** [comment]
22:31:53 [Error] [ShareManager] [vtcoin] Error getting account for pool central
wallet address: VbexsuZnG9h9t93Hz4DfhFxvcJ2KpJkogA - Unable to connect to the re
mote server
22:31:53 [Error] [JobManager] [vtcoin] New job creation failed: Unable to connec
t to the remote server
22:31:53 [Error] [JobManager] [vtcoin] New job creation failed: Unable to connec
t to the remote server
22:31:53 [Error] [JobManager] [vtcoin] New job creation failed: Unable to connec
t to the remote server
22:31:53 [Error] [BlockProcessor] [vtcoin] Error getting account for pool centra
l wallet address: VbexsuZnG9h9t93Hz4DfhFxvcJ2KpJkogA - Unable to connect to the
remote server
22:31:53 [Error] [NetworkInfo] [vtcoin] Can not read getdifficulty(): Unable to
connect to the remote server
22:31:53 [Error] [NetworkInfo] [vtcoin] Can not probe submitblock() support: Una
ble to connect to the remote server
22:31:53 [Error] [NetworkInfo] [vtcoin] Can not read getinfo(): Unable to connec
t to the remote server
22:31:53 [Error] [NetworkInfo] [vtcoin] Can not read getmininginfo(): Unable to
connect to the remote server
22:31:53 [Error] [NetworkInfo] [vtcoin] Can not read getblocktemplate(): Unable
to connect to the remote server

**Comment by zhq1** [comment]
My version is using the latest 0.25, compiled windows version

**Comment by jdghenderson** [comment]
Hi Zhq1, please can you download and compile this version:

https://github.com/vagabondan/CoiniumServ

It has more bug fixes although development has just stopped this is a much newer verison. If you have trouble please try the development branch and compile that. If your still having issues it will be with pool config files and specifically your wallet connection. Make sure no firewalls areblocknig or you dont have conflicting port setups on the machine your using,

There seem to be a few people with active forks of the project and I myself and actively using this version in production and it's working really well. I am just hoping someone else picks up this truely great pool software!

I am trying my best to learn more code to pick up the slack where I can.

Anyway hope this helps!

Kind Regards,

James

**Comment by zhq1** [comment]
@jdghenderson   Thank you for the answer, I will try to compile this version

**Comment by zhq1** [comment]
error: file not found: src/Tests/bin/Release/CoiniumServ.Tests.dll     @jdghenderson

**Comment by zhq1** [comment]
Could not locate your error view! Details: Unable to locate view 'error'
Currently available view engine extensions: sshtml,html,htm
Locations inspected: views//error-zh-CN,views//error,/error-zh-CN,/error,views/error-zh-CN,views/error,error-zh-CN,error
Root path: E:\0.3\web\default
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'

**Comment by laugh26** [comment]
Am having this not going pass it, i dont know why 

10:40:31 [Information] [ConfigManager] [global] CoiniumServ Aurora 0.2.5.2159 warming-up..
10:40:31 [Information] [PlatformManager] [global] Running over Mono 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017), framework: 4.5 (v4.0.30319.42000).
10:40:32 [Information] [ConfigManager] [global] Discovered a total of 0 enabled pool configurations: []
10:40:33 [Information] [WebServer] [global] Web-server listening on: http://localhost/

**Comment by bonesoul** [comment]
PoloniexClient and actually market managers should be disabled. I may give it a shot soon.
