### ISSUE TITLE
Siacoin with CoiniumServ ?

### ISSUE THREAD

**Issue by cycleworm** [bonesoul/CoiniumServ#856]
Hi Guys, 

does anybody know if it possible to setup a mining pool
for mining siacoin with CoiniumServ. 

Siacoin uses blake2b algorithm. 

Thanks.

**Comment by keepthefaya** [comment]
From the main page .... :+1: 

Algorithms

    Scrypt, SHA256d, X11, X13, X14, X15, X17, Blake, Fresh, Fugue, Groestl, Keccak, NIST5, Scrypt-OG, Scrypt-N, SHA1, SHAvite3, Skein, Qubit

**Comment by bonesoul** [comment]
https://github.com/bonesoul/CoiniumServ/blob/89d8c71012972981f97cb80ba4aecb95db7f1572/src/CoiniumServ/Algorithms/Implementations/Blake.cs

We have the implementation i guess if blake2b is no different then Blake.
