### ISSUE TITLE
keccak dificulty issues.

### ISSUE THREAD

**Issue by regtable** [bonesoul/CoiniumServ#858]
it has probably been asked but i cannot find it. using keccak algorythm what is the startum dificulty supposed to be around?
i know sha and scrypt are say 8+ and x11 is 0.01 or something like. whats keccak supposed to be? i tried 0.8 0.08 8 125 256   1025 and shares come back 0.00/setdiff but rejects as a low diff share and the guys mining submit 0.00 every time

**Comment by bonesoul** [comment]
i'm not sure about this. should be asking in actually keccak community i guess?
