### ISSUE TITLE
"Account has insufficient funds"

### ISSUE THREAD

**Issue by gecox22** [bonesoul/CoiniumServ#866]
I am having an issue. I can not for the life of me figure out.  Every the pool goes to make a payment it tells me Account Has insufficient funds.  My tables are set up correctly. I have rebuilt the pool numerous times. I have tried a new wallet. I checked the conf file for the wallet. I am mining DEM locally just to learn how pools work. Meaning My wallet is on local host the pool is on local host. Everything is connect from what I can see from the logs. When a block confirms I can see it is trying to make a payment for 49.54 and there is way more than that in the wallet. The wallet only has one account in the  listed as Pool. The Pool address is setup in the pool.json file. In the rewards portion of the .json file .1 goes to the pool wallet for fee and .9 goes to a personal wallet for testing I have tried making the rewards address all the same as the pool address that didn't work. Here is the Pool.json info 

`"daemon": {
	   "host": "127.0.0.1",
        "port": 6666,
        "username": "Supersecretusername ",
        "password": "Supersecretpassword"
    },
    "wallet": {
        "address": "NUTkKAoTcz9KhhLqi3aK2Ep1XCeVnUi68R",
        "txfee": 0.001
    },
    "rewards": [
        {
            "NUTkKAoTcz9KhhLqi3aK2Ep1XCeVnUi68R": 0.1,
            "NeFTEk6rYEZMFChTefvXwrdAffx7HdjXEm": 0.9
        }
`
My payment tables are set as decimal with a 0 in the box so it looks like 19,8 and then 0.00000000 I have check all my tables with another Pool owner that runs the same coin on his pool and we are both dumb founded.

I have also completely wiped the Redis and the MYSQL Databases and started from scratch. I have also tried a completely new database as well. 

I am completely stump any help would be greatly appreciated. I tried searching the issue and trying everything I could find before asking for help.

**Comment by gecox22** [comment]
Still having this issue. I have also tried turning off firewall and antivirus to see if that is the issue.(thinking something was blocking the pool server talking to my wallet)  I also had another pool owner build the server for me. Even though I receive errors on the webserver with his build the issue with "Account has insufficient funds" is still there when a block gets confirmed. This leads me to believe it is local to my pool server and my wallet. If any one has any ideas I would love to hear some. @bonesoul

**Comment by bonesoul** [comment]
Let's start simple. Does your coin wallet holds the actual funds?

**Comment by gecox22** [comment]
￼listaccounts
{
"" : 0.00000000,
"Pool" : 5796.08798200
}
getbalance Pool
5796.08798200

11/13/2017 03:05:39 -05:00 [Debug] [CoiniumServ.Payments.PaymentProcessor] [DeutscheEMark] Payment Outputs: [("NS42W2DSqxLxf1SJYZnojzue7fsYmfoeRs": 148.64700000)]
11/13/2017 03:05:39 -05:00 [Error] [CoiniumServ.Payments.PaymentProcessor] [DeutscheEMark] An error occured while trying to execute payment; "Account has insufficient funds"

**Comment by bonesoul** [comment]
Is those funds already confirmed by the network?

**Comment by gecox22** [comment]
Yes they are. I originally started this pool with a different wallet was having the same issue so, suggestion by another owner was to start everything fresh. I made a new database, deleted old wallet.dat. Started a new wallet input new address into pool.json saved started server and waited till blocks got mined. Mined block wait 90 confirms before payment is executed. So yes blocks are showing confirmed in wallet before coi

**Comment by gecox22** [comment]
Ok I rebuilt the pool. Deleted the wallet besides the appdata info. I transferred old wallet to the new wallet and still have insufficient funds. What am I missing here!!!!! Could it be my comouter or something I mean everything works besides payouts. I can't freaking understand what I am missing here.

**Comment by gecox22** [comment]
@bonesoul This was solved by uninstalling node 9.0.0 and installing node 8.7.0, I don't know why it fixed it or how. But that is the last thing I did while working on another project. I started the pool went to take a nap came back and payments started working. So I am closing this issue.

**Comment by supersausage007** [comment]
HI for anyone, who still has this issue: after trying various things, it turned out that the data structure in my coin database created a problem. I recreated the SQL table from scratch and payment distribution worked seamlessly from that point onward.

**Comment by ishikawa-pss9** [comment]
See also #1051 which fixed the issue in my case.

**Comment by ishikawa-pss9** [comment]
I spoke too soon, see issue #1055 for an SQL script that fixes the precision in the database, and pull request #1054 that makes the recipients pay the tx fee.
