### ISSUE TITLE
Restore Packages / Cannot Compile 

### ISSUE THREAD

**Issue by RegencySoftware** [bonesoul/CoiniumServ#867]
I restored the packages and it shows  Nancy.Viewengines.Razor.1.4.3 missing.  All the packages are in the package folder. Even after removing the reference and adding it back it seems the project does not find any of the packages.  This is when downloading from the master as a ZIP. 

All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.0408403
========== Finished ==========

https://i.imgur.com/1DtqghE.png

**Comment by gecox22** [comment]
I also ran into this. I found that If I used windows power shell to do the first part 
`git clone https://github.com/CoiniumServ/CoiniumServ.git
cd CoiniumServ
git submodule init
git submodule update` 

Then used visual studio's to build the project it worked. Kinda of followed these directions [https://github.com/bonesoul/CoiniumServ/wiki/Getting-Started:-Windows](url) I hope this helps

**Comment by bonesoul** [comment]
restore your nuget packages, should be fine then.
