### ISSUE TITLE
Paid: Complide version?

### ISSUE THREAD

**Issue by fr33rid3** [bonesoul/CoiniumServ#875]
Has the compiled version of CoiniumServe available for purchase been updated lately. All mining software on github seems to be several years out of date. I will buy the compiled version but only if it's up to date.
Ubuntu, Postgres and Mono will all be new versions???

**Comment by bonesoul** [comment]
Compiled version does not include Ubuntu, Postgres or Mono.
And yet again it doesn't include support.
