### ISSUE TITLE
Can't connect Bitcoin central wallet

### ISSUE THREAD

**Issue by mutlubilginonder** [bonesoul/CoiniumServ#879]
11/30/2017 05:46:57 +03:00 [Information] [ConfigManager] [global] CoiniumServ Atilla 0.2.6.2 warming-up..
11/30/2017 05:46:57 +03:00 [Information] [PlatformManager] [global] Running over Mono 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017), framework: 4.5
 (v4.0.30319.42000).
11/30/2017 05:47:03 +03:00 [Information] [PoolConfig] [Bitcoin] Disabled payment processor as it can not be enabled when MPOS mode is on
11/30/2017 05:47:03 +03:00 [Information] [ConfigManager] [global] Discovered a total of 1 enabled pool configurations: [Bitcoin]
11/30/2017 05:47:03 +03:00 [Information] [MySqlProvider] [Bitcoin] Mysql storage initialized: 127.0.0.1:3306, database: null.
11/30/2017 05:47:04 +03:00 [Error] [ShareManager] [Bitcoin] Error getting account for pool central wallet address: 1BRzvenBCjmGD8prnu4WfwsqzEE2rDWFuT -
 Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Information] [BanManager] [Bitcoin] No expired bans found to be cleared [remaining bans: 0].
11/30/2017 05:47:04 +03:00 [Error] [JobManager] [Bitcoin] New job creation failed: Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [JobManager] [Bitcoin] New job creation failed: Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [JobManager] [Bitcoin] New job creation failed: Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [BlockProcessor] [Bitcoin] Error getting account for pool central wallet address: 1BRzvenBCjmGD8prnu4WfwsqzEE2rDWFuT -
 Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [NetworkInfo] [Bitcoin] Can not read getdifficulty(): Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [NetworkInfo] [Bitcoin] Can not probe submitblock() support: Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [NetworkInfo] [Bitcoin] Can not read getinfo(): Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [NetworkInfo] [Bitcoin] Can not read getmininginfo(): Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Error] [NetworkInfo] [Bitcoin] Can not read getblocktemplate(): Error: ConnectFailure (Connection refused)
11/30/2017 05:47:04 +03:00 [Information] [NetworkInfo] [Bitcoin] symbol: BTC algorithm: sha256 version: null protocol: 0 wallet: 0
 network difficulty: 0.00000000 block difficulty: 0.00 network hashrate: 0.00 KH/s network: mainnet peers: 0 blocks: -2 errors: none
11/30/2017 05:47:04 +03:00 [Information] [StratumServer] [Bitcoin] Stratum server listening on 192.168.1.28:3333
11/30/2017 05:47:04 +03:00 [Error] [PoolManager] [global] Error recaching statistics; The method or operation is not implemented.

**Comment by bonesoul** [comment]
```
Error getting account for pool central wallet address: 1BRzvenBCjmGD8prnu4WfwsqzEE2rDWFuT -
Error: ConnectFailure (Connection refused)
```

check your coin daemon connectivity. this has nothing with coiniumserv.
