### ISSUE TITLE
Database Schema not being generated

### ISSUE THREAD

**Issue by exceeded** [bonesoul/CoiniumServ#882]
So I have created a database, and put all authentication details in correctly.

However, I'm presented with the following issues:

An exception occured while updating difficulty for miner; Table '<omitted>.pool_worker' doesn't exist
An exception occured while getting account; Table '<omitted>.pool_worker' doesn't exist

An exception occured while updating difficulty for miner; Unknown column 'username' in 'where clause'
An exception occured while getting account; Table '<omitted>.coin_addresses' doesn't exist

I can't find any schema data anywhere, and the only mention of it is in a forum post on bitcointalk about the software automatically generating and populating the database.

Any idea as to what I should do in this instance?

(I'm using MPOS and MySQL)

**Comment by bonesoul** [comment]
it should be created with mpos;

https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide#database-setup
