### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MihhaAcis** [bonesoul/CoiniumServ#884]
Hi, Guys! Could you tell me what i did wrong?
![img_20171211_205826_133](https://user-images.githubusercontent.com/34455107/33846208-f4e6d67e-deb6-11e7-922e-db9a515e7ae2.jpg)

**Comment by AndreyNag** [comment]
Для начала проверь логин-пароль от сервера к кошельку.

**Comment by MihhaAcis** [comment]
@AndreyNag Спасибо, пароль логин-пароль проверю (I will check my login-password from server to wallet)
Есть еще одна проблемка (there is another problem)
![111](https://user-images.githubusercontent.com/34455107/33874914-8357c0ba-df31-11e7-9331-7fb75c048110.png)

**Comment by MihhaAcis** [comment]
Make a right config))))
