### ISSUE TITLE
nuget restore the request timed out 

### ISSUE THREAD

**Issue by botio** [bonesoul/CoiniumServ#893]
botio@botio-ub:~/CoiniumServ/build$ nuget restore
Installing 'xunit.runner.console 2.3.1'.
Installing 'Newtonsoft.Json 10.0.3'.
Installing 'xunit.extensibility.core 2.3.1'.
Installing 'xunit.core 2.3.1'.
Installing 'xunit.assert 2.3.1'.
Installing 'Nancy.Hosting.Self 1.4.1'.
Installing 'AustinHarris.JsonRpc 1.1.70'.
Installing 'Microsoft.AspNet.Razor 3.2.3'.
Installing 'BouncyCastle 1.8.1'.
Installing 'FluentMigrator 1.6.2'.
Installing 'xunit.abstractions 2.0.1'.
Installing 'JsonConfig 1.0.0'.
Installing 'FluentMigrator.Runner 1.6.2'.
Installing 'StackExchange.Redis 1.2.6'.
Installing 'MySql.Data 6.8.8'.
Installing 'JsonFx 2.0.1209.2802'.
Installing 'Nancy 1.4.4'.
Installing 'xunit.analyzers 0.8.0'.
Installing 'ExposedObject 1.3.0'.
Installing 'ShouldFluent 1.1.19'.
Installing 'Gibbed.IO 1.0.0'.
Installing 'xunit.runner.visualstudio 2.3.1'.
Installing 'HashLib 2.0.1'.
Installing 'xunit 2.3.1'.
Installing 'Serilog 2.5.0'.
Installing 'Nancy.CustomErrors 1.2.0.0'.
Installing 'Nancy.Viewengines.Razor 1.4.3'.
Installing 'Serilog.Sinks.ColoredConsole 3.0.1'.
Installing 'Serilog.Sinks.RollingFile 3.3.0'.
Installing 'CryptSharpOfficial 2.1.0.0'.
Installing 'NSubstitute 1.7.2.0'.
Installing 'Serilog.Sinks.Console 3.1.1'.
Installing 'Nancy.Metrics 0.4.7'.
Installing 'Serilog.Sinks.File 4.0.0'.
Installing 'xunit.extensibility.execution 2.3.1'.
Installing 'Dapper 1.50.4'.
Installing 'Metrics.NET 0.5.3'.
The request timed out

Pls let me know how to fix ... thx

**Comment by bonesoul** [comment]
This is caused by the nuget service itself. Try again later.
