### ISSUE TITLE
Is CoiniumServ working better in Windows?

### ISSUE THREAD

**Issue by botio** [bonesoul/CoiniumServ#894]
I just wonder if the CoiniumServ working better in Windows than Linux.

If it is working better in Windows, I think I'll change to windows system for building.

Thank you so much. 

Or building CoiniumServ in VM of windows in a Linux PC will be the best solution for security? 

I just want to know the best and the most secure way to build.

**Comment by bonesoul** [comment]
OS security is another stuff you should be deciding on it's own.

Other then that, the code can work both on linux and windows.
