### ISSUE TITLE
error: file not found: src/Tests/bin/Release/CoiniumServ.Tests.dll

### ISSUE THREAD

**Issue by ludete** [bonesoul/CoiniumServ#897]
I'm using CoiniumServ-0.2.4-beta.
there have two issue;
1. when bash build/release/build.sh,  this need src/Tests/bin/Release/CoiniumServ.Tests.dll, but I dont't find this lib in project.
2. when compile the project from source code, don't find /root/CoiniumServ-0.2.4-beta/deps/csredis/CSRedis/CSRedis.csproj.

**Comment by bonesoul** [comment]
Skip the tests, you don't need them.

You have to submodule init.
