### ISSUE TITLE
download package misses folders & source code not VS2017 Pro compatible

### ISSUE THREAD

**Issue by acatogmbh** [bonesoul/CoiniumServ#899]
Hi

1. The download package of CoiniumServ does not match the documentation. forders that should be there are missing in zip file.

2. VS2017 Pro can not open project

2.1. when i open the project file in 

CoiniumServ-develop/build/CoiniumServ.sln 

I get an error in VS2017 Pro that it is not compatible.

2.2. If go to the source code in folder

CoiniumServ-develop/src/CoiniumServ/

I see no *.sln file 

There is only a CoiniumServ.csproj

how do i get this source code to be accepted in VS2017 so that i can start working on the compiling?

**Comment by BaalMcKloud** [comment]
https://github.com/bonesoul/CoiniumServ/blob/master/build/CoiniumServ.sln

i dont see any probs using VS15 and VS17
download the master branch as .zip

**Comment by acatogmbh** [comment]
I tested opening it with VS 2015 Pro. this worked. But since my Licence is now only valid for VS2017 I need to use it in this version.

When i open it in VS2017 it lits 2 project folders and claims they are incompatible.

Usually it should offer me to convert it into a new 2017 standard. That happens with my projects from VS2010/2013/2015 but strangely enough not with this one.

**Comment by acatogmbh** [comment]
I solve the Problem for now:
installed other components from VS2017 Installation but also started VS2017, then opened the Project file. then it showed "not compatible".

i selected each of the 2 Project nodes. richt clicked and told it to reload.

suddenly is was working,

Now i am looking to add a new x11 coin to the System. Where do i add this to the source code?

**Comment by acatogmbh** [comment]
issue solved
