### ISSUE TITLE
Deleted db, but execution is not creating it again

### ISSUE THREAD

**Issue by RSV70** [bonesoul/CoiniumServ#900]
I decided to change hybrit to mops, deleted all my sql database table and stoppepd redis serve.
Then I run coiniumserv. I expect it recreated database tables as it done afters first run, but it not recreateted tables. Looks like it has some flag saved about first run? How do I delete this, to start coiniumserv completely from beginning?

**Comment by bonesoul** [comment]
MPOS should initialize the DB itself.
