### ISSUE TITLE
600 errors 27 warnings

### ISSUE THREAD

**Issue by avandurmen0001** [bonesoul/CoiniumServ#901]
Pools/INetworkInfo.cs(102,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(44,6): error CS0246: The type or namespace name 'JsonObjectAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(44,6): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(44,17): error CS0103: The name 'MemberSerialization' does not exist in the current context
        Pools/IPoolConfig.cs(52,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(52,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(69,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPoolConfig.cs(69,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/NetworkInfo.cs(72,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(42,6): error CS0246: The type or namespace name 'JsonObjectAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(42,6): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(42,17): error CS0103: The name 'MemberSerialization' does not exist in the current context
        Pools/IPool.cs(50,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(50,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(53,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(53,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(56,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(56,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(61,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(61,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(64,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(64,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(67,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Pools/IPool.cs(67,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Pools/Pool.cs(104,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Blocks/BlockProcessor.cs(55,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(39,40): error CS0246: The type or namespace name 'JsonConverter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(41,40): error CS0246: The type or namespace name 'JsonWriter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(41,73): error CS0246: The type or namespace name 'JsonSerializer' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(46,41): error CS0246: The type or namespace name 'JsonReader' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(46,99): error CS0246: The type or namespace name 'JsonSerializer' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/DifficultyConverter.cs(41,30): error CS0115: 'DifficultyConverter.WriteJson(JsonWriter, object, JsonSerializer)': no suitable method found to override
        Daemon/Converters/DifficultyConverter.cs(46,32): error CS0115: 'DifficultyConverter.ReadJson(JsonReader, Type, object, JsonSerializer)': no suitable method found to override
        Daemon/Converters/DifficultyConverter.cs(63,30): error CS0115: 'DifficultyConverter.CanConvert(Type)': no suitable method found to override
        Daemon/Converters/TimeConverter.cs(41,34): error CS0246: The type or namespace name 'JsonConverter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/TimeConverter.cs(43,40): error CS0246: The type or namespace name 'JsonWriter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/TimeConverter.cs(43,73): error CS0246: The type or namespace name 'JsonSerializer' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/TimeConverter.cs(48,41): error CS0246: The type or namespace name 'JsonReader' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/TimeConverter.cs(48,99): error CS0246: The type or namespace name 'JsonSerializer' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Converters/TimeConverter.cs(43,30): error CS0115: 'TimeConverter.WriteJson(JsonWriter, object, JsonSerializer)': no suitable method found to override
        Daemon/Converters/TimeConverter.cs(48,32): error CS0115: 'TimeConverter.ReadJson(JsonReader, Type, object, JsonSerializer)': no suitable method found to override
        Daemon/Converters/TimeConverter.cs(67,30): error CS0115: 'TimeConverter.CanConvert(Type)': no suitable method found to override
        Daemon/Errors/RpcError.cs(37,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(37,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(37,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(37,46): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(40,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(40,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(40,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcError.cs(40,49): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Sockets/IConnection.cs(40,6): error CS0246: The type or namespace name 'JsonObjectAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Sockets/IConnection.cs(40,6): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Sockets/IConnection.cs(40,17): error CS0103: The name 'MemberSerialization' does not exist in the current context
        Server/Mining/Stratum/Sockets/SocketServer.cs(84,19): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Pools/PoolConfig.cs(65,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Pools/PoolManager.cs(51,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(38,6): error CS0246: The type or namespace name 'JsonObjectAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(38,6): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(38,17): error CS0103: The name 'MemberSerialization' does not exist in the current context
        Statistics/IStatisticsManager.cs(41,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(41,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(44,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(44,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(47,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/IStatisticsManager.cs(47,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Statistics/StatisticsManager.cs(58,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/IStratumMiner.cs(38,6): error CS0246: The type or namespace name 'JsonObjectAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/IStratumMiner.cs(38,6): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/IStratumMiner.cs(38,17): error CS0103: The name 'MemberSerialization' does not exist in the current context
        Daemon/Errors/RpcErrorResponse.cs(39,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(39,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(39,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(39,48): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/IStratumMiner.cs(51,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/IStratumMiner.cs(51,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(45,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(45,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(45,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(45,47): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(51,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(51,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(51,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Errors/RpcErrorResponse.cs(51,44): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/AuthenticationError.cs(36,40): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/DuplicateShareError.cs(37,40): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/JobNotFoundError.cs(37,37): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/LowDifficultyShare.cs(36,39): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/NotSubscriberError.cs(36,39): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Errors/OtherError.cs(36,31): error CS0246: The type or namespace name 'JsonRpcException' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Exceptions/RpcExceptionFactory.cs(38,26): error CS0246: The type or namespace name 'Meter' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumMiner.cs(303,27): error CS0246: The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumMiner.cs(114,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumMiner.cs(116,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonManager.cs(51,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(42,35): error CS0246: The type or namespace name 'JsonRpcService' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(57,10): error CS0246: The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(57,10): error CS0246: The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(78,10): error CS0246: The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(78,10): error CS0246: The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(93,10): error CS0246: The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/StratumService.cs(93,10): error CS0246: The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(37,6): error CS0246: The type or namespace name 'JsonArrayAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(37,6): error CS0246: The type or namespace name 'JsonArray' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/Block.cs(56,10): error CS0246: The type or namespace name 'JsonConverterAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/Block.cs(56,10): error CS0246: The type or namespace name 'JsonConverter' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(44,10): error CS0246: The type or namespace name 'JsonIgnoreAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(44,10): error CS0246: The type or namespace name 'JsonIgnore' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(51,10): error CS0246: The type or namespace name 'JsonIgnoreAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(51,10): error CS0246: The type or namespace name 'JsonIgnore' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(57,10): error CS0246: The type or namespace name 'JsonIgnoreAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Stratum/Responses/SubscribeResponse.cs(57,10): error CS0246: The type or namespace name 'JsonIgnore' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkMiner.cs(74,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkMiner.cs(76,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/Info.cs(53,10): error CS0246: The type or namespace name 'JsonConverterAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/Info.cs(53,10): error CS0246: The type or namespace name 'JsonConverter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(45,10): error CS0246: The type or namespace name 'JsonConverterAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(45,10): error CS0246: The type or namespace name 'JsonConverter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(65,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(65,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(68,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(68,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(71,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(71,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(74,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(74,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(77,10): error CS0246: The type or namespace name 'JsonIgnoreAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Responses/MiningInfo.cs(77,10): error CS0246: The type or namespace name 'JsonIgnore' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/CreateRawTransactionInput.cs(36,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/CreateRawTransactionInput.cs(36,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/CreateRawTransactionInput.cs(39,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/CreateRawTransactionInput.cs(39,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(36,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(36,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(39,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(39,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(42,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/Requests/SignRawTransactionInput.cs(42,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkServer.cs(48,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkService.cs(42,35): error CS0246: The type or namespace name 'JsonRpcService' could not be found (are you missing a using directive or an assembly reference?)
        Shares/ShareManager.cs(63,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkService.cs(62,10): error CS0246: The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Server/Mining/Getwork/GetworkService.cs(62,10): error CS0246: The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)
        Vardiff/VardiffManager.cs(46,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Cryptology/Hash.cs(99,16): error CS0246: The type or namespace name 'BigInteger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonBase.cs(58,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonBase.cs(60,33): error CS0246: The type or namespace name 'Meter' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(45,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(45,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(45,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(45,48): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(51,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(51,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(51,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(51,48): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(57,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(57,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(57,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonRequest.cs(57,44): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Logging/ILogTarget.cs(57,9): error CS0246: The type or namespace name 'LogEventLevel' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogTarget.cs(42,16): error CS0246: The type or namespace name 'LogEventLevel' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(42,23): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(148,35): error CS0246: The type or namespace name 'ILogEventEnricher' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(74,41): error CS0246: The type or namespace name 'LoggerConfiguration' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(113,36): error CS0246: The type or namespace name 'LoggerConfiguration' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(150,28): error CS0246: The type or namespace name 'LogEvent' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(150,47): error CS0246: The type or namespace name 'ILogEventPropertyFactory' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(130,38): error CS0246: The type or namespace name 'LoggerConfiguration' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(158,38): error CS0246: The type or namespace name 'ILogEventEnricher' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(160,28): error CS0246: The type or namespace name 'LogEvent' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(160,47): error CS0246: The type or namespace name 'ILogEventPropertyFactory' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(49,17): error CS0246: The type or namespace name 'LoggerConfiguration' could not be found (are you missing a using directive or an assembly reference?)
        Logging/LogManager.cs(50,17): error CS0246: The type or namespace name 'LoggerConfiguration' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(47,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(47,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(47,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(47,48): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Program.cs(49,24): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(53,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(53,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(53,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(53,44): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(59,10): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(59,10): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(59,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)
        Daemon/DaemonResponse.cs(59,47): error CS0246: The type or namespace name 'Order' could not be found (are you missing a using directive or an assembly reference?)
        Container/Registries/Registry.cs(42,25): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/Registries/Registry.cs(40,26): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/IObjectFactory.cs(155,9): error CS0246: The type or namespace name 'INancyBootstrapper' could not be found (are you missing a using directive or an assembly reference?)
        Container/Context/ApplicationContext.cs(36,16): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/Context/IApplicationContext.cs(36,9): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/Context/ApplicationContext.cs(38,35): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/Bootstrapper.cs(43,29): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/Bootstrapper.cs(41,26): error CS0246: The type or namespace name 'TinyIoCContainer' could not be found (are you missing a using directive or an assembly reference?)
        Container/ObjectFactory.cs(423,16): error CS0246: The type or namespace name 'INancyBootstrapper' could not be found (are you missing a using directive or an assembly reference?)
        Banning/BanManager.cs(53,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
        Configuration/ConfigManager.cs(73,26): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)

         27 Warning(s)
         600 Error(s)

Time Elapsed 00:00:01.7722170
Cannot open assembly 'contrib/xunit/xunit.console.clr4.x86.exe': No such file or directory.

**Comment by bonesoul** [comment]
restore nuget packages.
