### ISSUE TITLE
Just a quick help to build

### ISSUE THREAD

**Issue by ikolubr** [bonesoul/CoiniumServ#907]
Hi,
If I do this:
git clone https://github.com/CoiniumServ/CoiniumServ.git
cd CoiniumServ
git submodule init
git submodule update

Then you can compile the sources using;
cd build/release
./build.sh

The build folder just have a .gitignore file.

I also tried the https://github.com/bonesoul/CoiniumServ.git repo and got the same problem.

Can anyone point me to the right direction here, so I can start trying to build it!?

Thank you,

**Comment by gblass** [comment]
same issue here?

**Comment by bonesoul** [comment]
documentation is outdated;

`xbuild CoiniumServ.sln /p:Configuration="Release"`

you should be fine then.

**Comment by ikolubr** [comment]
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/Nancy.Viewengines.Razor.1.4.3/build/Nancy.ViewEngines.Razor.targets.

/CoiniumServ/CoiniumServ.csproj(503,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/Nancy.Viewengines.Razor.1.4.3/build/Nancy.ViewEngines.Razor.targets.

/CoiniumServ/src/Tests/Tests.csproj(121,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../packages/xunit.core.2.3.1/build/xunit.core.props.

Any help?

**Comment by bonesoul** [comment]
use nuget restore.

**Comment by rburkhal** [comment]
Also, you may get an error requiring an upgrade of nuget. Use the following command. Ensure that you also have the latest mono-complete(linux/osx).  Windows users should download the latest and install.

[Command]
nuget update -self

**Comment by crusher72** [comment]
When I update nuget or nuget update -self I get trust issues certificate invalid or decryption has failed

**Comment by nerdlabs001** [comment]
> When I update nuget or nuget update -self I get trust issues certificate invalid or decryption has failed

had to run in sudo but worked for me
