### ISSUE TITLE
Update Example Pools List

### ISSUE THREAD

**Issue by scottbasgaard** [bonesoul/CoiniumServ#916]
This list here:
- https://github.com/bonesoul/CoiniumServ/wiki/Pools

All sites are down or super scammy, can we clean this up?

**Comment by bonesoul** [comment]
sure you can edit the wiki page yourself

**Comment by scottbasgaard** [comment]
@bonesoul understood I just don't know of examples so if you have any let's get it updated or just remove it?

**Comment by scottbasgaard** [comment]
I'm new here, and that's the first thing I found to look at so wanted to give a heads up.

**Comment by bonesoul** [comment]
I'm not aware of any new pools yet, once so I'll update the list.
