### ISSUE TITLE
Building problem with 'Gibbed' on Ubuntu 17.10

### ISSUE THREAD

**Issue by nemoweb** [bonesoul/CoiniumServ#917]
Hi,
I am finding to build CoiniumServ for Ubuntu 17.10, i installed git and mono, but when i try to compile the source with:

`xbuild CoiniumServ.sln /p:Configuration="Release"`

i get the following error:

`Coin/Coinbase/Serializers.cs(36,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Coin/Coinbase/Utils.cs(38,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Jobs/Job.cs(44,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Transactions/GenerationTransaction.cs(42,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Transactions/Outputs.cs(38,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Transactions/Script/SignatureScript.cs(35,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
Utils/Extensions/ArrayExtensions.cs(34,7): error CS0246: The type or namespace name 'Gibbed' could not be found (are you missing a using directive or an assembly reference?)
			Task "Csc" execution -- FAILED
			Done building target "CoreCompile" in project "/home/xxxpool/xxx/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
		Done building project "/home/xxxpool/xxx/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/xxxpool/xxx/CoiniumServ/CoiniumServ.sln".-- FAILED
Done building project "/home/xxxpool/xxx/CoiniumServ/CoiniumServ.sln".-- FAILED

Build FAILED.`

i installed mono:

`Mono JIT compiler version 5.4.1.7 (tarball Wed Jan 17 20:26:34 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)`

and nuget:

`NuGet Version: 4.4.1.4656`

Thank in advance for the the help!

**Comment by bonesoul** [comment]
try a nuget restore first?

**Comment by nemoweb** [comment]
Perfect! It works!
Thank a lot!
