### ISSUE TITLE
System.OverflowException: 

### ISSUE THREAD

**Issue by jeong760** [bonesoul/CoiniumServ#937]
Dears,

I have a bitcoin core 15.0 and when I running a CoiniumServ only bitcoin pool have a following error so it cannot initialized properly. why does errors occurred and how does it prevent?

PC 
- i7 8700 (6 Cores)
- 24GB memory in total

SW
- Bitcoin core 15.0
- Globaltoken 2.1

Pool
- Bitcoin < -- it has a following error
- Globaltoken (no problem to running)

01/30/2018 07:44:38 +09:00 [Error] [Pool] [Bitcoin] Pool initilization failed; Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.INetworkInfo ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Pools.NetworkInfo ---> System.Exception: There was a problem deserializing the response from the coin wallet. ---> Newtonsoft.Json.JsonSerializationException: Error converting value 1.84523889606798E+19 to type 'System.UInt64'. Path 'result.networkhashps', line 1, position 185. ---> System.OverflowException: 

Regards,
John Ahn

**Comment by regtable** [comment]
same error....... hoping for help

**Comment by bonesoul** [comment]
dupliate of #933
