### ISSUE TITLE
can not find  ./CoiniumServ

### ISSUE THREAD

**Issue by bobozm** [bonesoul/CoiniumServ#941]
Ubuntu server 16.04.3
no bin file after build

**Comment by bonesoul** [comment]
so? you need to build it?

**Comment by bobozm** [comment]
ran build twice

**Comment by bonesoul** [comment]
check build/bin folder

**Comment by bobozm** [comment]
found it

**Comment by bobozm** [comment]
did it build properly

**Comment by bobozm** [comment]
ok thanks got it to run with mono
