### ISSUE TITLE
Where is the .sql file?

### ISSUE THREAD

**Issue by hellomotow** [bonesoul/CoiniumServ#945]
Where is the .sql file I can use? I want to get statics working.

**Comment by bonesoul** [comment]
mpos should be creating it for you.

**Comment by hellomotow** [comment]
14:57:42 [Error] [HybridStorage] [Bitcoin] An exception occured while getting block; Table 'coinium.Block' doesn't exist
14:57:42 [Error] [HybridStorage] [Bitcoin] An exception occured while getting block; Table 'coinium.Block' doesn't exist
14:57:42 [Error] [HybridStorage] [Bitcoin] An exception occured while getting block totals: Table 'coinium.Block' doesn't exist

**Comment by bonesoul** [comment]
Use mpos to create them then.
