### ISSUE TITLE
Getting [WebServer] error after start

### ISSUE THREAD

**Issue by drinkOut** [bonesoul/CoiniumServ#951]
Hi. I've built coiniumServ and now I am trying to start pool for litecoin mining, but error occurs:

00:53:39 [Error] [WebServer] [global] Can not listen on requested interface: localhost - The process cannot access the file because it is being used by another process

Pool and wallet are installed locally

What can be the reason of such error and how can I fix it?

**Comment by jeong760** [comment]
Dears,

Change the web server port to another such as 8080 and try to connect it through http://localhost:8080

**Comment by drinkOut** [comment]
It works now.
Thank you!
