### ISSUE TITLE
How to run server

### ISSUE THREAD

**Issue by bnleach** [bonesoul/CoiniumServ#954]
I have successfully compiled the server on ubuntu 1404 and edited the configuration files. How do I run the server ?

**Comment by bonesoul** [comment]
run it with mono.

**Comment by bnleach** [comment]
what would the command line be? I tried using the ./CoiniumServ and that did not work. It threw out an error

**Comment by bnleach** [comment]
I also tried running with mono using "mono-service CoiniumServ.exe" and it did nothing . I checked using sudo service --status-all and coiniumserv was not running. I am out of ideas. Please advise how to run this softwar on ubuntu 14.04 as I have everything up to this complete(compiled and configured)

**Comment by bnleach** [comment]
Never mind. I was able to get it going.

**Comment by tiny-tinker** [comment]
@bnleach Please let me know how did you solve it. Thanks.
