### ISSUE TITLE
Blocks found but listed as rejected by daemon

### ISSUE THREAD

**Issue by ilushka85** [bonesoul/CoiniumServ#964]
I know people have posted this before but is there any way to resolve?

**Comment by ilushka85** [comment]
@bonesoul  any ideas on this?

**Comment by bonesoul** [comment]
give more details please, which blockchain?

**Comment by ilushka85** [comment]
Bonesoul.  So i added logic (didn't send pr yet as im testing) that looks at the response from submitblock to see if its successful (should return null string) and added retry logic like you had suggested for errors.

The problem i am having however is that afterwards it calls GetBlock and this fails with block not found.  For some reason the block hash is incorrect eventhough the block hex was accepted.  In looking back on the block afte rsubmission and acceptance it very clearly has a different block hash then what i see in the output of coinium


It is for raven coin  https://github.com/RavenProject/Ravencoin

It should be a straight copy of bitcoind with the replacement of x16r.

My x16r algo submisisons are currently wrong.  I have a pr to fix them. i am sending now.

For comparisson:

yiimp version working:
https://github.com/tpruvot/yiimp/blob/88cfe6faf7b003d290d0d831e13cdc2e94d9a42a/stratum/algos/x16r.c

my final version which appears to be correct:
https://github.com/ilushka85/CoiniumServ/blob/develop/src/CoiniumServ/Algorithms/Implementations/X16r.cs

**Comment by ilushka85** [comment]
Ok so i made corrections to the algo again .  Will push in a minute.  Still i am seeing that for a block we are submititng correctly but the blockhash we are calculating is somehow wrong

**Comment by ilushka85** [comment]
So the share appears valid and submitted and credited but the blockhash does not match the block after submission.  Thoughts?

**Comment by ilushka85** [comment]
Found the cause... the block header is hashed differently.  We need to move away from using getblock as a check for if block exists after a successful submit

**Comment by ilushka85** [comment]
I created blocknotify system to deal with this.  will send pr
