### ISSUE TITLE
Json validation failed for : config/pools/default.json/ Help with Databases!

### ISSUE THREAD

**Issue by heginbotham1** [bonesoul/CoiniumServ#965]
This is the error that is happening I cannot get these databases to work.

Here is my problem!
http://i.imgur.com/ZOJ8rvK.png

**Comment by bonesoul** [comment]
use this https://jsonlint.com/

**Comment by heginbotham1** [comment]
Databases are still failing can you take a look? 
https://i.imgur.com/fcVuMjE.png

**Comment by BenKnigge** [comment]
Do you have mysql running on the port that you have configured in the config file and does the user that you have set in the config file have full permissions to the database?

**Comment by heginbotham1** [comment]
yes
