### ISSUE TITLE
Databases Failing!

### ISSUE THREAD

**Issue by heginbotham1** [bonesoul/CoiniumServ#966]
Databases are still failing can you take a look?
https://i.imgur.com/fcVuMjE.png

**Comment by BenKnigge** [comment]
I had many issues as well until I made sure to downgrade the MySqlData package to 6.8.8 and StackExchange.Redis to 1.2.4 I had updated them to the latest in my project but the newer versions were causing an issue.

**Comment by heginbotham1** [comment]
Sorry I still haven't figured this out I don't know whats wrong? can anyone help?

**Comment by BenKnigge** [comment]
The error means that you don't have MySQL running and accessible on the port that you've configured.

**Comment by heginbotham1** [comment]
I do have it running :/

**Comment by heginbotham1** [comment]
It connected when I didn't put a database down.

**Comment by heginbotham1** [comment]
@BenKnigge I can send configs without password 🏷 If thats ok?

**Comment by BenKnigge** [comment]
Maybe you should hire someone more experienced to set this up for you.

**Comment by heginbotham1** [comment]
I know what I am doing this software is just not working

**Comment by BenKnigge** [comment]
Set up a cheap VPS and give me access to it and I'll  configure it for you. I'm guessing that you haven't setup the mysql server correctly or created a user with the proper permissions.

**Comment by heginbotham1** [comment]
Ok sure how should I send the info? thanks :D

**Comment by heginbotham1** [comment]
Discord? Stormrider#5388 thats all I have and I am not sending it over github sorry Thanks for the offer 👍 !

**Comment by heginbotham1** [comment]
@BenKnigge thanks for offering to help!

**Comment by BenKnigge** [comment]
I would be interested in knowing what the problem and solution ultimately was.

**Comment by heginbotham1** [comment]
hmm so how could you help me sorry for closing it I am a little impatient

**Comment by heginbotham1** [comment]
Could you set it up?

**Comment by heginbotham1** [comment]
*fixed*
