### ISSUE TITLE
Database Failing *Config's Included*

### ISSUE THREAD

**Issue by heginbotham1** [bonesoul/CoiniumServ#970]
Sorry for creating this ticket again I won't create anymore if you can't help me sorry.

Ok so my databases are failing as you see here 
https://imgur.com/a/UXk4L

and here are my configs for my pools without passwords

default.json
https://pastebin.com/SFisVc5c

pool.json
https://pastebin.com/n7dpZYrj

and yes I do have lyracoin.json working and the lyracoin network working.

**Comment by jeong760** [comment]
@heginbotham1, Have you created a database name of **lyracoin** om MySql? I think your problem you did not create a database on MySql side.  CoiniumServ needs to create a database first on MySql and then it automatically created a table on it.

**Comment by heginbotham1** [comment]
I did but how do I define that in the config is it correct?

**Comment by heginbotham1** [comment]
*fixed*

**Comment by BenKnigge** [comment]
Was the issue that you didn't create the DB?

**Comment by heginbotham1** [comment]
Nope

**Comment by BenKnigge** [comment]
So what was the issue?
