### ISSUE TITLE
Change blockchain explorer URL

### ISSUE THREAD

**Issue by heginbotham1** [bonesoul/CoiniumServ#973]
How do I change the blockchain url from altexplorer to my blockchain explorer url

**Comment by jeong760** [comment]
You can add them in your coin.json under config/coins folder. Please open  a bitcoin.json on same folder and see how to

**Comment by jeong760** [comment]
See following links as an example
https://github.com/bonesoul/CoiniumServ/blob/develop/config/coins/bitcoin.json

**Comment by heginbotham1** [comment]
already *fixed*
