### ISSUE TITLE
Found Bug Unhandled rpc-exception 

### ISSUE THREAD

**Issue by heginbotham1** [bonesoul/CoiniumServ#974]
Here I think I found a bug please fix
Unhandled rpc-exception: An unknown exception occurred while making json request

Screenshot:
https://imgur.com/a/JzYwQ

**Comment by jeong760** [comment]
@heginbotham1, which coin daemon do you enconter a this issue?

**Comment by heginbotham1** [comment]
oh Its LyraCoin
