### ISSUE TITLE
coin daemon -getinfo RPC

### ISSUE THREAD

**Issue by SmarterHomes** [bonesoul/CoiniumServ#990]
-getinfo was removed by core in 0.15
the RPC command itself is back now in 0.16 just to answer with the DEPRECATED information

but since it's there again, the server recognises it an tries to get the information from there. it should be defaulted the other way.

**Comment by jeong760** [comment]
@HashUnlimited Your issue has been solved so you need to do a git pull and compiles again, please

**Comment by SmarterHomes** [comment]
thx, looks good so far

**Comment by SmarterHomes** [comment]
getting back to work and testing: here's a small remaining detail to be fixed: test chains aren't displayed properly, the chain should be extracted from `getblockchaininfo` RPC

log entry on testnet when starting up: `network: mainnet`

**Comment by jeong760** [comment]
@HashUnlimited  could you sync and recompile with the last update?

**Comment by SmarterHomes** [comment]
currently I don't have any test instance running because we have already forked and here we do not support features like Dash's superblocks. I'll close for now and check back when I can free a test server.
