### ISSUE TITLE
 [Ubuntu] Redis database connection fails

### ISSUE THREAD

**Issue by SmarterHomes** [bonesoul/CoiniumServ#992]
As our target is to move from MPOS to hybrid storage, we started on our test servers without success. We already know that mono isn't fully supported on Ubuntu 17.10, we changed to 16.04 but are still not able to go with redis (Redis 4.0.8 (00000000/0) 64 bit) -> redis-cli ping answers PONG

command line output (logs basically saying the same):

12:20:55 [Error] [RedisProvider] [CrapCoin] Redis storage initialization failed: 127.0.0.1:6379
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. 
  at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl (System.Func`1[TResult] multiplexerFactory, System.IO.TextWriter log) [0x0008f] in <3c6615c26745427097f34fa88a9ec796>:0 
  at StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) [0x0000d] in <3c6615c26745427097f34fa88a9ec796>:0 
  at CoiniumServ.Persistance.Providers.Redis.RedisClient..ctor (System.String host, System.Int32 port, System.String password, System.String extraOptions) [0x0007a] in <c12d79403a0e4c129f9c5cec0d154f09>:0 
  at CoiniumServ.Persistance.Providers.Redis.RedisProvider.Initialize () [0x00022] in <c12d79403a0e4c129f9c5cec0d154f09>:0

**Comment by jeong760** [comment]
Could you post here your CrapCoin pool config after removed a sensitive info?

**Comment by jeong760** [comment]
Does it works before?

**Comment by SmarterHomes** [comment]
tbh before I was always using a SQL / MPOS combo but now since we have several updated coins I am looking for the hybrid solution for the final production setup. 

here's the config:

`{
    # detailed sample config file for pool which explicility sets all settings.

	"enabled": true,	

    # -------------------------------
    # Coin configuration
    # -------------------------------

    # coin: name of the coin configuration file that should exist in config/coins/.

	"coin": "chaincoin.json",    

    # -------------------------------
    # Coin Daemon RPC Connection
    # -------------------------------

	# host: ip/hostname of coin-daemon.
    # port: the port coin daemon is listening on.
    # username: username for rpc connection.
    # password: password for rpc connection.

	"daemon": {
		"host": "127.0.0.1",
		"port": 21995,
		"username": "rpcuser",
		"password": "letstakeasecureonehere"
	},

    # -------------------------------
    # Meta Configuration
    # -------------------------------

    # motd: message of the day.
    # txMessage: message to be included used within generation transactions.

    "meta": {
        "motd": "Welcome to CoiniumServ pool, enjoy your stay! - http://www.coiniumserv.com",
        "txMessage": "http://www.coiniumserv.com/"
     },

    # -------------------------------
    # Wallet & Rewards Configuration
    # -------------------------------
    
    # address: generated coins will arrive here.

    "wallet" : {
        "address":  "ZKB8rS7nunQksBc6WB9ipsNJxp915Z48uF"
    },

    # rewards: list of addresses that gets a percentage from each mined block (ie, pool fee.)

    "rewards":  [
        {"ZRhzw5rApPqCKzEC2wynGGwGbWxyjZrZK3": 1} 
    ],

    # -------------------------------
    # Payment Processing Configuration
    # -------------------------------

	# enabled: set this true to let CoiniumServ handle the payments, false if you would like some other software like mpos to handle them.
    # interval: interval in seconds that payment-processor will be running.
    # minimum:  minimum amount of coins before a miner is eligable for getting a payment.

	"payments": {
		"enabled": false,
        "interval": 60,
		"minimum": 0.01
	},

    # -------------------------------
    # Miner Configuration
    # -------------------------------

    # validateUsername: set true to validate miner usernames as an addresses against the coin daemon.
    # timeout: timeout in seconds to disconnect miners that did not submit any shares for the period.

    "miner":  {
        "validateUsername": true,
        "timeout": 300
    },

    # -------------------------------
    # Job Manager Configuration
    # -------------------------------

    # blockRefresh: timeout in miliseconds to poll coin daemon for a new block.
    # rebroadcast: if now new blocks are found in this many seconds, a new job will be created and broadcasted.


    "job":  {
        "blockRefreshInterval": 1000,
        "rebroadcastTimeout": 55        
    },

    # -------------------------------
    # Stratum Server Configuration
    # -------------------------------

    # stratum:
    # enabled: set this true to enable stratum server.
    # bind: interface to bind stratum server.
    # port: port to listen for stratum connections.
    # diff: default difficulty assigned to newly connected miners.

    # vardiff:
    # enabled: set this true to enable variable-difficulty support.
    # minDiff: minimum difficulty that can be assigned to miners.
    # maxDiff: maximum difficulty that can be assigned to miners.
    # targetTime: try to get a single share per this many seconds from miner.
    # retargetTime: retarget a miners difficulty ever this many seconds.
    # variancePercent: allow difficulty for a miner to vary this percent without retargeting.

	"stratum": {
		"enabled": true,
		"bind": "0.0.0.0",
		"port": 3334,
		"diff": 128,
        "vardiff": {
            "enabled": true,
            "minDiff": 1,
            "maxDiff": 1028,
            "targetTime": 5,
            "retargetTime": 90,
            "variancePercent": 70
        }
	},
    			
    # -------------------------------
    # Ban Configuration
    # -------------------------------

    # you can ban miners which submits invalid work / data to reduce system/network load.
    # enabled: set this true to enable banning support.
    # duration: duration of ban when a miner gets flagged for so.
    # invalidPercent: percentage of invalid shares to trigger a ban.
    # checkThreshold: number of shares required before a miner's shares are considered for a ban.
    # purgeInterval: purge interval in seconds that bans are checked to see if they are expired.

    "banning": {
        "enabled": true,
        "duration": 600,
        "invalidPercent": 50,
        "checkThreshold": 100,
        "purgeInterval": 300
    },

    # -------------------------------
    # Per-pool Storage Configuration
    # -------------------------------

    # hybrid storage layer
    # enabled: set this true to enable hybrid storage mode where redis and mysql is used together.

    # mpos layer
    # enabled: set this true to enable mpos compatibility mode - make sure to internal disable payment-processor!

    # redis
    # host: redis host.
    # port: redis port.
    # password: set the password if your redis installation requires one.
    # databaseId: redis database instance id (optional)

    # mysql
    # host: database host.
    # port: database port.
    # username: username for connecting the database.
    # password: password for connecting the database.
    # database: database name.

	"storage": {
        "hybrid": {
            "enabled": true,
		    "redis": {
			    "host": "127.0.0.1",
			    "port": 6379,
                "password": "",
                "databaseId": 0
		    },
		    "mysql": {
			    "host": "127.0.0.1",
			    "port": 3306,
			    "user": "root",
			    "password": "insecure",
                "database": "testnet"
		    }
        },
        "mpos": {
            "enabled": true,
		    "mysql": {
			    "host": "127.0.0.1",
			    "port": 3306,
			    "user": "root",
			    "password": "insecure",
                "database": "mpos"
		    }
        }
	},  

    # -------------------------------
    # Getwork Server Configuration
    # -------------------------------

    # EXPERIMENTAL!; This feature is still in development and not complete yet.
    # enabled: Set this true to enable getwork server.
    # bind: interface to bind getwork server.
    # port: port to listen for getwork connections.

	"vanilla": {
		"enabled": false,
		"bind": "localhost",
		"port": 2223
    }
}
`

**Comment by RepoBike** [comment]
I get the same thing after the new git pull / repo

**Comment by RoomanSr** [comment]
Did this get solved ? I am having the same problem.

**Comment by dmshel** [comment]
reload from repo and recompile 
or try my solution #987

**Comment by SmarterHomes** [comment]
working now, thx
