### ISSUE TITLE
Configuring proper Redis server on Ubuntu 16 server

### ISSUE THREAD

**Issue by bomb-on** [bonesoul/CoiniumServ#999]
I suppose this is very much related to #826 and #975, but since I never worked with C# I just cannot figure out from comments how to properly install `Stackexchange.Redis` on Ubuntu 16.04 from command line. I tried to install Redis with `sudo apt install redis-server` first and I was getting an error when starting the pool: `Redis storage initialization failed: 127.0.0.1:6379` although the Redis was running.

After reading mentioned issues, I uninstalled current Redis with `sudo apt remove redis-server` and tried to build it from source:
```
wget https://github.com/StackExchange/StackExchange.Redis/archive/1.2.6.tar.gz
tar xf 1.2.6.tar.gz
cd StackExchange.Redis-1.2.6
./monobuild.bash
```
but I hit the same error during the build:
```
Building StackExchange.Redis.dll ...
StackExchange.Redis/StackExchange/Redis/MessageQueue.cs(37,25): warning CS0219: The variable `peeked' is assigned but its value is never used
StackExchange.Redis/StackExchange/Redis/SocketManager.cs(121,22): warning CS0414: The private field `StackExchange.Redis.SocketManager.useHighPrioritySocketThreads' is assigned but its value is never used
Compilation succeeded - 2 warning(s)
Building BasicTest.exe ...
Running basic test ...

Unhandled Exception:
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
  at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl (System.Func`1[TResult] multiplexerFactory, System.IO.TextWriter log) [0x00098] in <6de82d252bb142f2aba063217c30bedd>:0
  at StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) [0x0000d] in <6de82d252bb142f2aba063217c30bedd>:0
  at BasicTest.Program.Main () [0x00000] in <8cd70ebbe3114a298a2c4d5166b54c55>:0
[ERROR] FATAL UNHANDLED EXCEPTION: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. UnableToResolvePhysicalConnection on PING
  at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl (System.Func`1[TResult] multiplexerFactory, System.IO.TextWriter log) [0x00098] in <6de82d252bb142f2aba063217c30bedd>:0
  at StackExchange.Redis.ConnectionMultiplexer.Connect (System.String configuration, System.IO.TextWriter log) [0x0000d] in <6de82d252bb142f2aba063217c30bedd>:0
  at BasicTest.Program.Main () [0x00000] in <8cd70ebbe3114a298a2c4d5166b54c55>:0
```

I know this is not Coinium issue at all, but since it is a requirement to run pool correctly, would you be so kind to provide some info how to install `StackExchange.Redis` properly and run it as a system service (or make Coinium aware of this installation) on Ubuntu 16.04 without any GUI or any extra Microsoft-related tools?
Or, if that's not possible for this or that reason, what exactly to do with compiled dlls which can be found in mentioned issues? How to make Ubuntu and Coinium aware to use a specific dll after downloading one?

Thanks a lot in advance!

**Comment by dmshel** [comment]
My solution #987

**Comment by bomb-on** [comment]
@dmshel Thanks a lot for this quick answer!! However, I still don't quite understand how exactly you got those `dll` and `xml` files and made pool aware of this Redis?

If I build it manually with:
```
wget https://github.com/StackExchange/StackExchange.Redis/archive/1.2.6.tar.gz
tar xf 1.2.6.tar.gz
cd StackExchange.Redis-1.2.6
./monobuild.bash
```
I can see `dll` file but not `xml`. If I copy `dll` file to my pool folder and run it with `sudo mono CoiniumServ.exe` I still have the same Redis error.

If I use `nuget` to "install" it:
```
sudo nuget install StackExchange.Redis
```
I can find both `dll` and `xml` but again, copying them to pool's folder doesn't change anything, I still have the same error :/

**Comment by dmshel** [comment]
pls look  ~/CoiniumServ/packages
 ~/CoiniumServ/packages/StackExchange.Redis.1.2.4/lib/net46
![default](https://user-images.githubusercontent.com/37098267/37705441-9c4abea6-2d2e-11e8-8639-b689f826914b.JPG)
![default](https://user-images.githubusercontent.com/37098267/37705795-c0fbe634-2d2f-11e8-9cb1-1a7f432a28bb.JPG)

**Comment by dmshel** [comment]
StackExchange.Redis from nuget package

**Comment by bomb-on** [comment]
Ok, I think I got it...

First of all, Redis server **must be** installed, of course, so I run `sudo apt install redis-server` again.

Then, after cloning Coinium, running `nuget restore` and building everything, I copied those 2 files from `packages/StackExchange.Redis.1.2.6/lib/netstandard1.5/` folder because `dll` and `xml` from other 2 folders (`packages/StackExchange.Redis.1.2.6/lib/net45/` and `packages/StackExchange.Redis.1.2.6/lib/net46/`) resulted in the same Redis error after starting the pool...

I am facing some other errors now (`Halted as daemon we are connected to does not own the pool address`) but I've seen some issues regarding that, will try to figure it out :)

Thanks @dmshel for helping!!
